### ISSUE TITLE
The implementation of IG-MSA is different from the diagram in the paper.

### ISSUE THREAD

**Issue by lartpang** [caiyuanhao1998/Retinexformer#1]
In the released code, this module is implemented as spatial self-attention, but in fact as we can see from the diagram, this is actually channel self-attention.

https://github.com/caiyuanhao1998/Retinexformer/blob/650e41c9798eae313dca52db3fd5e628581799ed/basicsr/models/archs/RetinexFormer_arch.py#L158-L171

![image](https://github.com/caiyuanhao1998/Retinexformer/assets/26847524/9991c7f0-139b-48ec-80b3-19fdb4ae26c0)

**Comment by caiyuanhao1998** [comment]
hello, thanks for your attention.

This diagram is channel-wise self-attention, the same as our implementation.

Please note that the shape of channel self-attention map is " C x C " while that of spatial attention is " HW x HW "

**Comment by lartpang** [comment]
@caiyuanhao1998 

Oh, sorry, I missed the code to adjust the shape. Thank you very much for your reply.

**Comment by caiyuanhao1998** [comment]
You are welcome. 

我关注了你的github。你写的 pytorch tricks 看着很有用，之后做实验可以安排上了，哈哈～

**Comment by davidL-zhan** [comment]
您好我想问一下 您有试过用spatial self-attention 吗 效果怎样 或者和channel self-attention的区别是什么 会干扰空间顺序吗
