### ISSUE TITLE
RuntimeWarning: Mean of empty slice.

### ISSUE THREAD

**Issue by shangyueweiliang** [caiyuanhao1998/Retinexformer#10]
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
===>Testing using weights:  /home/cy/Retinexformer/Retinexformer-master/pretrained_weights/pretrain_model/LOL_v1.pth
data/LOLv1/Test/input
data/LOLv1/Test/target
0it [00:00, ?it/s]
/home/cy/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/cy/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
PSNR: nan 
SSIM: nan 

So,what should i do?thank you

**Comment by caiyuanhao1998** [comment]
For `RuntimeWarning: Mean of empty slice` , you are calling the mean function on an empty slice, i.e., you are asking for the mean no values at some point in your program.

Please insert some breakpoints in your program to have a check.

I guess you may mistaken some paths

**Comment by nameOfjinshuai** [comment]
我也遇到了这个问题，现在已经解决了。我的原因在于lol数据集的存放目录不正确。
LOLv1应该存放在Retinexformer-master的data目录下（即需要自己先在Retinexformer-master下创建一个data目录），而不是存放在basicsr的data目录下。

如图所示：
![截屏2023-12-28 15 20 06](https://github.com/caiyuanhao1998/Retinexformer/assets/147959400/43ae9a81-d21c-4012-9844-e86ea45a2b70)

**Comment by chaoyue12345678** [comment]
> 我也遇到了这个问题，现在已经解决了。我的原因在于lol数据集的存放目录不正确。 LOLv1应该存放在Retinexformer-master的data目录下（即需要自己先在Retinexformer-master下创建一个data目录），而不是存放在basicsr的data目录下。
> 
> 如图所示： ![截屏2023-12-28 15 20 06](https://private-user-images.githubusercontent.com/147959400/293157504-43ae9a81-d21c-4012-9844-e86ea45a2b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTI2MDgsIm5iZiI6MTcwMzc1MjMwOCwicGF0aCI6Ii8xNDc5NTk0MDAvMjkzMTU3NTA0LTQzYWU5YTgxLWQyMWMtNDAxMi05ODQ0LWU4NmVhNDVhMmI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODMxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGU5MTJkZDdhMzkwNTBhNzQyNmE1NzZiMTVmMjk2OTQ1ZDhhMmNmYTk3MmRiZTY0ZTE5MDMyMGE1NmY5NjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0xHQ-TRp418tE5qosX1jWpM6ZDhL-jxaHUFN093zvhk)

可以看一下你的数据集放哪里了 和你的测试代码吗 看哪里不合适

**Comment by SaadAhmad376** [comment]
I am having the same issue even though my paths are correct. BTW I'm trying it for NTIRE.

**Comment by chaoyue12345678** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月26日(星期五) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [caiyuanhao1998/Retinexformer] RuntimeWarning: Mean of empty slice. (Issue #10)














 
I am having the same issue even though my paths are correct. BTW I'm trying it for NTIRE.
