### ISSUE TITLE
关于模型拟合问题

### ISSUE THREAD

**Issue by MoWangDaRen** [caiyuanhao1998/Retinexformer#103]
请问您是如何判断模式是否拟合呢，好像只有一条l_pix曲线。

**Comment by MoWangDaRen** [comment]
是否过拟合

**Comment by caiyuanhao1998** [comment]
在训练过程中，定期测在训练集和测试集上的指标，如果训练集上增高但是测试集上变低就是过拟合了。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢

**Comment by MoWangDaRen** [comment]
> 在训练过程中，定期测在训练集和测试集上的指标，如果训练集上增高但是测试集上变低就是过拟合了。
> 
> 如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢

log中的l_pix指标是训练集上的吗,可以详细说一下测试集的指标在哪查看吗，在您的日志中没有看到测试集的指标，tensorboard也只绘制了l_pix与psnr两条训练集的指标
