### ISSUE TITLE
The size of RAW and RGB images in the MIT-Adobe FiveK dataset is inconsistent

### ISSUE THREAD

**Issue by XiaMu799** [caiyuanhao1998/Retinexformer#104]
Hello, the RAW and RGB image sizes of the MIT-Adobe FiveK dataset I downloaded are inconsistent, how did you solve this problem?

**Comment by caiyuanhao1998** [comment]
Hi, we just use the raw datasets to output the sRGB images. Please have a look at this issue:

https://github.com/nothinglo/Deep-Photo-Enhancer/issues/38

To make things easier, you can directly download our processed sRGB low- and normal-light image pairs in the [Baidu Disk](https://pan.baidu.com/s/1ajax7N9JmttTwY84-8URxA?pwd=cyh2) (code:cyh2) and [Google Drive](https://drive.google.com/file/d/11HEUmchFXyepI4v3dhjnDnmhW_DgwfRR/view?usp=sharing)

If you find our repo useful, please help us star it, thanks :)
