### ISSUE TITLE
sid数据集数量问题

### ISSUE THREAD

**Issue by ycwsilent** [caiyuanhao1998/Retinexformer#106]
我从你给出的goole网盘下载下来sid_processed数据集
但是我看里面的long_sid2里面的每一个文件夹内只有一个文件；但是你给出的目录结构它包含多个
是我下载错了吗
这个是你给出的结构
![4ec90767d4b2cd0d6d9be585a1ce9c9](https://github.com/user-attachments/assets/897c34cd-f670-489f-a8bf-71d7117bda8f)

我下载的结构
![image](https://github.com/user-attachments/assets/2f07530e-ddb8-4647-a08b-60b42fd9c4f8)

**Comment by caiyuanhao1998** [comment]
这个文件夹应该是正确的。我们可能没用到 00001 文件夹。你可以看看其他的文件夹，应该包含了多个曝光时间的数据对。

我们用的这个数据链接也是直接从之前的工作那边 copy 来的，你可以查看一下：

https://github.com/dvlab-research/SNR-Aware-Low-Light-Enhance?tab=readme-ov-file

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢
