### ISSUE TITLE
How to get the enhanced image

### ISSUE THREAD

**Issue by peter-parker-wang** [caiyuanhao1998/Retinexformer#108]
The dataroot_gt and dataroot_lq paths in the configuration file are high-quality and low-quality pictures respectively. By enhancing the images in the dataroot_lq folder, we can compare them with the images in the dataroot_gt folder. Through test_from_dataset.py, we can get data such as psnr, and in the result, we can get the different images of the contrast image, but what I want to ask is how can I get the enhanced image. It is an image compared with the dataroot_gt folder. Where is it kept?
Thank you for your answer!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

The enhanced results are saved at 

https://github.com/caiyuanhao1998/Retinexformer/blob/master/Enhancement/test_from_dataset.py#L199

in the folder `./results/`. Please check that.

If you find our repo useful, please help us star it, thank you :)
