### ISSUE TITLE
怎么用已经训练好的模型测试自己的一张暗光图像

### ISSUE THREAD

**Issue by rilixianren** [caiyuanhao1998/Retinexformer#109]

**Comment by caiyuanhao1998** [comment]
你好，只需要修改 config 里面的路径指向你的图像即可。

如果觉得我们的repo有用的话，麻烦帮我们点点 star 支持一下，感谢 :)

**Comment by rilixianren** [comment]
你好，我现在有一张自己的暗光图片，如何利用lolv1模型对自己的这张暗光图片进行处理，并将增亮后的图片进行保存？

**Comment by caiyuanhao1998** [comment]
修改 config 里面的路径指向你的图像，然后运行 test_from_dataset.py

**Comment by thelin1** [comment]
> 好的，非常感谢，我再去试一试 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yuanhao Cai ***@***.***&gt; 发送时间: 2024年9月14日 00:34 收件人: caiyuanhao1998/Retinexformer ***@***.***&gt; 抄送: rilixianren ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [caiyuanhao1998/Retinexformer] 怎么用已经训练好的模型测试自己的一张暗光图像 (Issue #109) 修改 config 里面的路径指向你的图像，然后运行 test_from_dataset.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，请问您是如何解决这个问题的，我在进行复现时同样遇到了相似的问题。我将config和dataset修改如下：
`dataset = 'Retinexformer-master\Enhancement\mydata'
config = 'Retinexformer-master\Enhancement\mydata'`
但是最终也会出现报错问题，感谢您的解答

**Comment by zhangjy328** [comment]
> 修改 config 里面的路径指向你的图像，然后运行 test_from_dataset.py

config在哪里？能写一个清晰的测试步骤吗？
