### ISSUE TITLE
反卷积带来的上采样尺寸不一致

### ISSUE THREAD

**Issue by MidsummerHi** [caiyuanhao1998/Retinexformer#111]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 212 but got size 213 for tensor number 1 in the list.

我单独把RetinexFormer拎出来进行测试，我输入图片后就报错了上面是报错的内容，我溯源后发现是反卷积导致的尺寸不一致。大概是下采样的是213，在反卷积回来就变成212了，这咋整。

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，

我的建议是，把输入图像先 padding 到 4 的倍数，具体可以参考以下代码：

https://github.com/caiyuanhao1998/Retinexformer/blob/master/Enhancement/test_from_dataset.py#L166

这样子上采样时，尺寸就可以对齐了。

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下吧，感谢 :)
