### ISSUE TITLE
MIT-Adobe FiveK数据集训练结果掉点问题

### ISSUE THREAD

**Issue by dadaplm** [caiyuanhao1998/Retinexformer#112]
您好，在MIT-Adobe FiveK数据集上训练时发现结果掉点比较厉害，验证结果“PSNR”指标一直都在17点多，
<img width="315" alt="截屏2024-09-16 17 20 23" src="https://github.com/user-attachments/assets/0b4e621d-ec72-4a5a-8609-75ffbac59c74">
但是使用您给出的训练权重进行测试时，结果与论文一致，请问这是是什么问题？
感谢您在低光增强上的贡献。

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，我可以提供一些调试思路供你参考一下：

我认为可能是pytorch版本不一致导致的，在Loss_PSNR( )的实现中，使用了一些torch.nn的内置函数，可能不同版本对一些异常值的处理方式不同。你可以：

改一下pytorch的版本到我们推荐的版本，或者换一种不需要pytorch，只使用numpy和math的计算psnr的方法：
```shell
import math
def calc_psnr(img1, img2, data_range=255):
    img1 = img1.clamp(0., 1.).mul_(data_range).cpu().numpy()
    img2 = img2.clamp(0., 1.).mul_(data_range).cpu().numpy()
    img1 = img1.astype(np.float64)
    img2 = img2.astype(np.float64)
    mse = np.mean((img1 - img2)**2)
    if mse == 0:
        return float('inf')
    return 20 * math.log10(255.0 / math.sqrt(mse))
```

然后检查一下 MIT-Adobe 数据是否是 sRGB output mode，可以直接从我们在 `README.MD` 里面留下的链接进行下载。

然后是训练的时候，参考我们的 training log 进行对齐。希望能帮到你。

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下吧，感谢 :)
