### ISSUE TITLE
Result really bad testing on real-life image

### ISSUE THREAD

**Issue by willswordh** [caiyuanhao1998/Retinexformer#116]
I tested many pictures that are shot in the dark, and I tried the model of LOLv2-real, the results are really bad after the model processing. Which pre-trained model is best for real-life images?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

I did not try to enhance the out-of-distribution images. I suggest you to write a for-loop code to test all of our models and pick up the best. Which one is the best depends on which dataset best matches the testing image.

If you find our repo useful, please help us star it, thanks :)

**Comment by willswordh** [comment]
@caiyuanhao1998 Hi Yuanhao, thanks for your reply! From your knowledge, which dataset is more related to real-life low dark images with lots of noise? Thanks!

**Comment by caiyuanhao1998** [comment]
I think the NTIRE dataset would be better

If you find our repo useful, please help us star it, thanks :)
