### ISSUE TITLE
[Help] Comparison Experiment

### ISSUE THREAD

**Issue by xv994** [caiyuanhao1998/Retinexformer#117]
Hello!

Thank you for your contribution to the field of low light image enhancement.
I would like to ask for your help! Can you provide the images provided by the algorithm used in the comparison experiment?
Because of the excellent performance of your work, I have cited your paper in my paper. However, I found comparison experiment is too time-consuming for my devices. I only have one 2060Ti, so it's difficult for me to finish the integral experiment.

Thank you for your time!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

We share more results of compared baseline methods to help your research. Feel free to download them from [Google Drive](https://drive.google.com/drive/folders/1P75bv6jBp8UxcLDhqMACvIQXck2sS9da?usp=sharing) or [Baidu Disk](https://pan.baidu.com/s/1ksGGV6nMyVVE6OqGuyO8_w?pwd=cyh2) 😄

If you find our repo useful, please help us star it, thanks :)
