### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by yyydfff** [caiyuanhao1998/Retinexformer#118]
为什么我训练的模型pth文件用来测试psnr只有23？
Why is the PTH file of the model that I trained used to test PSNR only 23

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Please check our training log and train our model on 3090 for FiveK and LOLv2, and RTX 8000 for other datasets.

If you find our repo useful, please help us star it, thanks :)
