### ISSUE TITLE
没有GPU可以用CPU复刻运行结果吗

### ISSUE THREAD

**Issue by Musuro77** [caiyuanhao1998/Retinexformer#119]
rt，纯小白电脑上没有GPU,测试运行的时候报错ssertionError: Torch not compiled with CUDA enabled，请问有办法解决吗

**Comment by caiyuanhao1998** [comment]
你好，感谢关注

我觉得只用 cpu 的话挺难的，建议还是要有显卡，可以去 codalab 租 GPU 算力时间，一个月大概 70 多，还行，够用。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢 :)
