### ISSUE TITLE
关于模型复现

### ISSUE THREAD

**Issue by thelin1** [caiyuanhao1998/Retinexformer#120]
作者您好，我在尝试用此代码增强自己的低光图像时，遇到了一些问题，

1. `config = '\mydata\HW.png'`，我查找之前的issue，看到一个您的解答，然后将config改成这样。但是在测试中会有如下报错
`D:\anaconda\envs\Pytorch\Lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\anaconda\envs\Pytorch\Lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)`
  感谢您的回复

**Comment by kkkadw** [comment]
请问解决了吗
