### ISSUE TITLE
Testing on images with lots of noise returns bad result 

### ISSUE THREAD

**Issue by willswordh** [caiyuanhao1998/Retinexformer#121]
@caiyuanhao1998 Hi Yuanhao, I am testing to use your model to process low-light pictures that have lots of noise which are shot from not-advanced cameras. The direct result is not good. Do you recommend to apply some deep-learning based denoise model first to the image, then use your model to process it? Or will it make the result even worse? Hope to get some insight from you, thanks a lot!

**Comment by caiyuanhao1998** [comment]
Hi, it would be better you switch to our other enhancement models that can handle severe image degradation

I suggest you try SID and SMID models.

If you found our repo useful, please help us star it, thanks :)

**Comment by willswordh** [comment]
@caiyuanhao1998 Hi Yuanhao, SID and SMID models are for raw pictures. Is my understanding right that for pictures like jpg, the general low light enhancement models trained on LOL like datasets will not be able to handle severe image degradation? I am thinking to apply some denoise models based on jpg pictures to eliminate noise then apply your model to do enhancement. Not sure if it is gonna work out. Please share your insight. Thanks!

**Comment by willswordh** [comment]
@caiyuanhao1998 Please offer your valuable insight if you are able to see this

**Comment by MohamAbdi** [comment]
@willswordh Hi willswordh, Have you managed to resolve the issue? I'm encountering the same problem. When the model enhances the image, it also amplifies the noise. Even after applying a deep-learning-based denoising model, I couldn't completely remove the noise. Any suggestions?
