### ISSUE TITLE
Unzip the dataset

### ISSUE THREAD

**Issue by LQchen1** [caiyuanhao1998/Retinexformer#122]
I would like to ask what is the meaning of z01 and zip file joint decompression? Also, don't you need to download files with the z02 and z03 suffixes

**Comment by caiyuanhao1998** [comment]
Hi, it's wierd, because I can successfully unzip the files with bandzip software,

Please use [bandizip](https://www.bandisoft.com/bandizip/) to jointly unzip the .zip and .z01 files of SMID, SDSD-indoor, and SDSD-outdoor

**Comment by LQchen1** [comment]
> 你好，这很奇怪，因为我可以使用 bandzip 软件成功解压文件，
> 
> 请使用[bandizip](https://www.bandisoft.com/bandizip/)联合解压SMID、SDSD-indoor、SDSD-outdoor的.zip和.z01文件

![image](https://github.com/user-attachments/assets/c2a3fba9-65ed-4b83-82ad-b29b0dc0aaf1)
我不太明白联合解压是什么意思？是将相同的.z01和.zip文件先后解压到同一个目录下吗？另外我还发现Fivek数据集的标签有一些文件似乎也发生了损坏。

**Comment by LQchen1** [comment]
> > 你好，这很奇怪，因为我可以使用 bandzip 软件成功解压文件，
> > 请使用[bandizip](https://www.bandisoft.com/bandizip/)联合解压SMID、SDSD-indoor、SDSD-outdoor的.zip和.z01文件
> 
> ![image](https://private-user-images.githubusercontent.com/93528700/376428960-c2a3fba9-65ed-4b83-82ad-b29b0dc0aaf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTg3NTksIm5iZiI6MTcyODk1ODQ1OSwicGF0aCI6Ii85MzUyODcwMC8zNzY0Mjg5NjAtYzJhM2ZiYTktNjVlZC00YjgzLTgyYWQtYjI5YjBkYzBhYWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyMTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjhhYjk2NGMyNDNhMmRmYTgxNjI5ZGM5MjRjMTdlYWIwYmMwZWYyZmM4NmY4ZGE4ODJlNGI4ZmZiYjAwODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sVu58WBU6gxUWfivS251E2tKlWGJ1rYx70ntjfZMs60) 我不太明白联合解压是什么意思？是将相同数据集的.z01和.zip文件先后解压到同一个目录下吗？另外我还发现Fivek数据集的标签文件夹下有一些图片似乎也发生了损坏。

Fivek我重新通过百度网盘的链接（之前是谷歌的链接）下载了他，现在解压是正常的，但是.z01这个问题还是没有解决
