### ISSUE TITLE
你好，在LOLv1上的复现精度和论文精度差异大，论文是25.16，我只得到了23.16，我没有改动任何代码，请问我需要怎么调整呢？

### ISSUE THREAD

**Issue by LQchen1** [caiyuanhao1998/Retinexformer#123]
![image](https://github.com/user-attachments/assets/2f3cea99-944e-497b-b048-c9eb4fef635d)

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上边训练的。请按照我们的 readme 里面的步骤配置环境并执行环境。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下

**Comment by LQchen1** [comment]
> 你好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上边训练的。请按照我们的 readme 里面的步骤配置环境并执行环境。
> 
> 如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下

我再多跑几次吧，我是在A100上跑的，按照原始的batchsize的话显存占用很低，
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    mini_batch_sizes: [8]  
    我之前改了这三个参数，分别为32,64,64，服务器的cpu的核心是80，但是数据加载非常慢，这是什么原因呢？

**Comment by Bin-ze** [comment]
> 好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上训练的。您请按照我们的 readme 里面的步骤配置环境并执行环境。
> 
> 如果觉得我们的repo有用的话，帮忙点点star支持一下



> 你好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上边训练的。请按照我们的 readme 里面的步骤配置环境并执行环境。
> 
> 如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下

您好，我尝试LOLV1上训练您的模型，但是得到了跟楼上同样的结果。
我注意到您一直在强调您使用RTX 8000得到了论文中的指标。我的训练是在4090上进行的。
我想知道，不同显卡之间的差异可以有这么大吗？
非常棒的工作！同时也期待您的解惑

**Comment by Houruizhi** [comment]
> > 好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上训练的。您请按照我们的 readme 里面的步骤配置环境并执行环境。
> > 如果觉得我们的repo有用的话，帮忙点点star支持一下
> 
> > 你好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上边训练的。请按照我们的 readme 里面的步骤配置环境并执行环境。
> > 如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下
> 
> 您好，我尝试LOLV1上训练您的模型，但是得到了跟楼上同样的结果。 我注意到您一直在强调您使用RTX 8000得到了论文中的指标。我的训练是在4090上进行的。 我想知道，不同显卡之间的差异可以有这么大吗？ 非常棒的工作！同时也期待您的解惑

+1. 原程序一点都没改，在LOL-V1上，PSNR 22.5383

**Comment by dongzhetao** [comment]
+1.原程序我也一点没改，在LOL-V1上，psnr也就23不到。我是3090的卡

**Comment by Houruizhi** [comment]
> +1.原程序我也一点没改，在LOL-V1上，psnr也就23不到。我是3090的卡

我这两天又跑了几次，调了调学习率和数据增强，也才跑到23.5几... 有没有开发人员能回答一下呀

**Comment by dongzhetao** [comment]
> @dongzhetao @Houruizhi 我感觉这个代码就是不稳定，我觉得原因可能是为了降低Transformer的复杂度，将注意力权重变成了C*C，这样会限制Transformer的表达能力，让模型陷入低秩风险，另外，我觉得光照点亮模块设计得过于简单，导致无法很好的学习到暗光以及噪声环境下图像的光照分布，不过作者的引入噪声的思路确实很棒，我基于上述两点做了一篇改进再结合了其他的改进方法，模型就变得稳定多了。希望对你们有所帮助。 ![image](https://private-user-images.githubusercontent.com/93528700/396407723-b48683fa-04c1-4a8e-b6fe-d609cbc0a001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjM1NDIsIm5iZiI6MTczNDQyMzI0MiwicGF0aCI6Ii85MzUyODcwMC8zOTY0MDc3MjMtYjQ4NjgzZmEtMDRjMS00YThlLWI2ZmUtZDYwOWNiYzBhMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjMxMTg3MzM3NGRmNzAwZTE5NDIyYzBlYzYyMjRjMTIwMTgyYjYyZjA3Y2YwMzIzNzhiYjNiYjFkNGY3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GPNZDPe2cgk0Hgk1vN5ItXyw0eC1cFwHZoXxDCe-BaY)

可以分享一下您的工作吗？是写了一篇论文吗？

**Comment by LQchen1** [comment]
@dongzhetao 刚投了个B1出去，我们这篇工作比较急，没有做更多的数据集，有些模块的设计仍然不是很优雅，如果有机会我们未来想做得更好，使用更多的数据集或者做更多的图像增强任务，希望到时候能给大家分享我们的工作，这篇论文中了，我们也会考虑开源代码给大家分享。总的来说，我们的工作也是基于Retinexformer工作上的改进，对Retinex理论引入噪声，然后使用更好的模块去去噪。可以关注一下Retinexformer的另一篇近期工作Retinexmamba，通过引入更好的Vmamba算子来提升模型的性能。https://github.com/YhuoyuH/RetinexMamba?tab=readme-ov-file

**Comment by X-Ichigo** [comment]
> [@dongzhetao](https://github.com/dongzhetao) [@Houruizhi](https://github.com/Houruizhi) 我感觉这个代码就是不稳定，我觉得原因可能是为了降低Transformer的复杂度，将注意力权重变成了C*C，这样会限制Transformer的表达能力，让模型陷入低秩风险，另外，我觉得光照点亮模块设计得过于简单，导致无法很好的学习到暗光以及噪声环境下图像的光照分布，不过作者的引入噪声的思路确实很棒，我基于上述两点做了一篇改进再结合了其他的改进方法，模型就变得稳定多了。希望对你们有所帮助。 ![image](https://github.com/user-attachments/assets/b48683fa-04c1-4a8e-b6fe-d609cbc0a001)
您好，请问是如何实现25.79的指标呢，拜读了您的论文在LOL-v1数据集上的结果是24.025呀，求教

**Comment by ldshuihen** [comment]
@X-Ichigo 请问您是在哪里看的论文啊？论文名叫什么啊？怎么修改代码提高psnr的？

**Comment by ldshuihen** [comment]
@LQchen1 请问是如何实现25.79的指标啊？有公开的代码或论文吗？

**Comment by LQchen1** [comment]
@dongzhetao @X-Ichigo @ldshuihen 你们好，我们的论文已经被《煤炭科学技术》期刊录用，这是我们投稿的论文，后续可以在知网查询。

[基于Retinex理论的解耦级联去噪的低光图像增强方法6.16.pdf](https://github.com/user-attachments/files/21335728/Retinex.6.16.pdf)

**Comment by X-Ichigo** [comment]
> [@dongzhetao](https://github.com/dongzhetao) [@X-Ichigo](https://github.com/X-Ichigo) [@ldshuihen](https://github.com/ldshuihen) 你们好，我们的论文已经被《煤炭科学技术》期刊录用，这是我们投稿的论文，后续可以在知网查询。
> 
> [基于Retinex理论的解耦级联去噪的低光图像增强方法6.16.pdf](https://github.com/user-attachments/files/21335728/Retinex.6.16.pdf)

感谢您的回复
