### ISSUE TITLE
您好想问一下关于模型修改的问题

### ISSUE THREAD

**Issue by studier111** [caiyuanhao1998/Retinexformer#126]
我在服务器上同时修改了两个Retinexformer的工程文件，用的是同一个环境，但第二个修改的模型在训练时总是读取的是我第一个修改过后的文件参数，所以我把第一个文件的model_type换了个名字，第二个修改的模型就报错/Retinexformer-master/Retinexformer-master/basicsr/models/__init__.py", line 36, in create_model
    raise ValueError(f'Model {model_type} is not found.')
ValueError: Model ImageCleanModel is not found.

**Comment by caiyuanhao1998** [comment]
你好，感谢关注

如果你需要修改模型的网络结构的话，需要把模型重命名成 "*_arch.py"

然后再 init.py 里面，会自动检索这种命名的模型文件，将其注册。

如果想指定导入某一模型，需要在 config 文件里面修改模型名称

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下吧 :)

**Comment by studier111** [comment]
谢谢！已点star，想询问一下注册具体是什么含义？还有config文件在文件夹的哪个位置？

**Comment by studier111** [comment]
是所指的.yml文件中的name还是model_type吗？
