### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by 348330** [caiyuanhao1998/Retinexformer#128]
您好，我在训练当中遇到了一个问题，想向您请教一下，一开始我在lolv1和lolv2_real、sid数据集上均能正常训练，但是当我开始准备在lolv2_syn数据集上训练时，突然报错ModuleNotFoundError: No module named 'wandb'，如下图所示：
![image](https://github.com/user-attachments/assets/e2647ee6-3005-455d-9e20-fc6ebe3bad86)
然后接下来我在相同环境下，重新对lolv1、lolv2_real、sid数据集进行训练，发现lolv1和lolv2_real也会报ModuleNotFoundError: No module named 'wandb'这个错误，但是sid数据集能够正常训练，我的环境中没有安装wandb这个库，请问一下可以解答一下吗？
![image](https://github.com/user-attachments/assets/0f3f593e-aa35-44c2-910b-f4b0b3e3d4bb)

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，
 
wandb (weights and bias) 是一个能够监督训练过程的很好的 debug 的可视化工具，能够 visualize 训练损失函数，各种超参变化。理论上没有这个包也是可以训练的，我写了 .txt 的 logger。不过你想从训练中获得更多的信息的话，建议还是安装一下这个包，hhh

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢 :)

**Comment by 348330** [comment]
已经点星了hhh，感谢回答，我还想请问一下，如果不想安装wandb库的话，应该怎么样去解决ModuleNotFoundError: No module named 'wandb'这个报错呢？

**Comment by caiyuanhao1998** [comment]
感谢，直接把 wandb 所有相关的代码注释掉就好了，hhh
