### ISSUE TITLE
使用torch2环境时，按照步骤安装后报错ImportError: cannot import name 'create_dataloader' from 'basicsr.data' (/home/l/.local/lib/python3.9/site-packages/basicsr/data/__init__.py)

### ISSUE THREAD

**Issue by liuwanqingqing** [caiyuanhao1998/Retinexformer#129]

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，这个问题是没有正确安装 basicsr 包导致的，建议你按照我们 readme 里面的步骤安装 basicsr

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢 :)

**Comment by liuwanqingqing** [comment]
你好，我就是按照torch 2的安装步骤进行的，报出的这个错误，目前pytho=3.9,安装的版本是Finished processing dependencies for basicsr==1.2.0+1.4.2可以麻烦检查看一下问题在哪里吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yuanhao Cai ***@***.***&gt;
发送时间: 2024年10月28日 12:52
收件人: caiyuanhao1998/Retinexformer ***@***.***&gt;
抄送: LLL ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [caiyuanhao1998/Retinexformer] 使用torch2环境时，按照步骤安装后报错ImportError: cannot import name 'create_dataloader' from 'basicsr.data' (/home/l/.local/lib/python3.9/site-packages/basicsr/data/__init__.py) (Issue #129)





 
你好，感谢关注，这个问题是没有正确安装 basicsr 包导致的，建议你按照我们 readme 里面的步骤安装 basicsr
 
如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢 :)

**Comment by XunpengYi** [comment]
这个问题似乎是CUDA 12.x和torch 2.x同时使用，安装basicsr时导致的，在CUDA 11.x时似乎不会遇到这个问题。请问您解决了吗？

**Comment by zhuohai2363** [comment]
这个问题怎么就解决啊，我也遇到了
