### ISSUE TITLE
Unable to reproduce the effect of the original text

### ISSUE THREAD

**Issue by climberwu** [caiyuanhao1998/Retinexformer#132]
Hello author, the PSNR of your transformer reproduced on LOLv1 is 23.45, which does not match the one in the article!
May I ask what caused it?

**Comment by caiyuanhao1998** [comment]
Hi, thansk for your interest.

Please use 3090 to train our model on LOL-v2-synthetic and FiveK datasets and use RTX 8000 to train on other datasets.

You can refer to our training log for your convenience to debug. 

If you find our repo useful, please help us star it, thanks :)

**Comment by climberwu** [comment]
Thank you, may I ask if there are any other graphics cards that can replace RTX8000? The laboratory does not have this graphics card.I would like to use this paper as a baseline and humbly seek your advice！
