### ISSUE TITLE
关于Illumination Prior（Lp）、Light-up Feature（Flu）以及Light-up Map

### ISSUE THREAD

**Issue by Liu-zhi-chao** [caiyuanhao1998/Retinexformer#133]
您好，非常感谢您的出色工作，对我启发很大，有几个问题想咨询一下：
（1）Illumination Prior是必要的吗？直接用原始图像生成后续的I_lu以及F_lu行吗？
（2）网络是如何确保生成的Light-up Map和Light-up Feature是我们想要的呢？
（3）如果把 I_re直接去掉，假设I_en = I_lu，这满足Retinex理论吗？
（4）如果我只想获取原图像的光照特征，不需要图像增强，只利用卷积生成的F_lu用于后续利用可靠吗？

**Comment by caiyuanhao1998** [comment]
你好感谢关注：
(1) 如果想提升性能的话，illu prior 可以加上。嫌麻烦的话可以去掉。
(2) 这个是通过 end-to-end 训练得到的
(3) 满足
(4) 可以试一下

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下吧，感谢 :)

**Comment by love-whut** [comment]
> 您好，非常感谢您的出色工作，对我启发很大，有几个问题想咨询一下： （1）Illumination Prior是必要的吗？直接用原始图像生成后续的I_lu以及F_lu行吗？ （2）网络是如何确保生成的Light-up Map和Light-up Feature是我们想要的呢？ （3）如果把 I_re直接去掉，假设I_en = I_lu，这满足Retinex理论吗？ （4）如果我只想获取原图像的光照特征，不需要图像增强，只利用卷积生成的F_lu用于后续利用可靠吗？

你好，请问下用卷积生成的F_lu效果好吗，我的数据集是无监督的，不是配对的，感觉效果不太行
