### ISSUE TITLE
关于GT-Mean

### ISSUE THREAD

**Issue by studier111** [caiyuanhao1998/Retinexformer#134]
您好，感谢您对低光增强领域做出的贡献，想问一下如果不想使用gtmean怎么修改？我在test_from_dataset里把关于gtmean的都注释掉了，用有gtman训练出来的权重pth去测试，测试出来的psnr和ssim都没有任何改变，这是为什么？

**Comment by caiyuanhao1998** [comment]
你好，GT-mean 默认是不使用的，训练的时候也不会带 GT-mean，只有测试的时候会用到。但是我不建议你用这个 trick，感觉有点像是在作弊。之前很多方法用，如果为了和他们比的话，可以用一下

**Comment by caiyuanhao1998** [comment]
默认就是取消的。不需要特别取消，如果要是用的话，需要在命令里面加上 action `--GT_mean`

**Comment by studier111** [comment]
感谢您的解答，如果我通过您的模型修改后的模型，加上--GT_mean后测试增幅只有0.02您知道大概是因为什么吗
