### ISSUE TITLE
关于点亮图像的问题

### ISSUE THREAD

**Issue by LQchen1** [caiyuanhao1998/Retinexformer#136]
很棒的工作，有一个小问题想请教您一下，按照论文以及Retinex理论的逻辑，在得到Lp之后应该直接与img做逐元素乘积就完成图像的点亮了，但在代码中，我看您在逐元素相乘之后还加上了原图像img，请问这样的原因是什么呢？https://github.com/caiyuanhao1998/Retinexformer/blob/5c74b0d74316372b4a7b093c4a3b38601e14b621/basicsr/models/archs/RetinexFormer_arch.py#L337

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，这是 residual learning 的思想，因为直接学一个点乘，数值上可能不稳定，训练不好优化。所以改成学残差了。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下噢
