### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by hkz01** [caiyuanhao1998/Retinexformer#137]
后边的几个数据解压的时候提示损坏了，可以重新上传一下吗

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，请问你具体指哪些数据呢？有一些数据得用 README 里面指定的软件来进行解压的

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下吧，感谢 :)

**Comment by hkz01** [comment]
.z01  .z02用bandzip打开都显示文件已损坏是什么原因呢
