### ISSUE TITLE
LOL数据集怎样在多卡上进行训练

### ISSUE THREAD

**Issue by liuwanqingqing** [caiyuanhao1998/Retinexformer#138]

**Comment by caiyuanhao1998** [comment]
你好，感谢关注

请使用我们 NTIRE 的多卡训练代码，然后把数据路径换成 LOL 数据集即可

其实 LOL 训练很快的，单卡也用不了多长时间

如果觉得我们的 repo 有用的话，麻烦帮我们点点 star 支持一下，感谢！
