### ISSUE TITLE
code about illumination estimator

### ISSUE THREAD

**Issue by MSL502** [caiyuanhao1998/Retinexformer#14]
In the illumination estimator, the paper mentions that 1×1 convolution is followed by 9×9 convolution, but the convolution kernel of the next convolution after 1×1 convolution is set to 5×5 in the code. May I ask what the correct convolution kernel is set to

**Comment by caiyuanhao1998** [comment]
5×5 is correct.
9×9 is a typo, I forgot to revise that, sorry.
