### ISSUE TITLE
Please！

### ISSUE THREAD

**Issue by Dr-zhang691** [caiyuanhao1998/Retinexformer#140]
How are the illumination feature maps, illumination maps, and illumination enhancement images generated?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests

the illumination feature maps, illumination maps, and illumination enhancement images are obtained by our illuminations estimator.

Please refer to Figure 2 of our paper
<img width="1118" alt="截屏2024-11-13 上午8 25 26" src="https://github.com/user-attachments/assets/7dc5c096-89c5-445d-9ef0-d980350ecd77">

**Comment by Dr-zhang691** [comment]
> 您好，感谢您的关注
> 
> 照明特征图、照明图和照明增强图像由我们的 Illuminations Estimator 获得。
> 
> 请参阅我们论文的图 2 <img alt="截屏2024-11-13 上午8 25 26" width="1118" src="https://private-user-images.githubusercontent.com/48472661/385776208-7dc5c096-89c5-445d-9ef0-d980350ecd77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDU3NzIsIm5iZiI6MTczMTUwNTQ3MiwicGF0aCI6Ii80ODQ3MjY2MS8zODU3NzYyMDgtN2RjNWMwOTYtODljNS00NDVkLTllZjAtZDk4MDM1MGVjZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTI3OWIzOTQ5M2NmNTAzMGEyODQxMzdhMzQ1ZDA4NWYyNmE3MWQ3M2FiYTM3Nzk1MWY5NGI2ODI3MmI4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O0KOBflIGF18_EDQfVy-h7Ohn7aBXq04PRdAyBNAn5Y">

Thank you for your reply. Could you please specify which part of your code reflects this, and is it possible to visualize it?
