### ISSUE TITLE
Please need some guidance and overview on Running the model without CUDA or alternate Backends

### ISSUE THREAD

**Issue by navjotschahal** [caiyuanhao1998/Retinexformer#141]
Hi Please help me understand how to run the model without cuda or using alternate backend system . Where in the code I can see and modularly try to disable or change cuda acceleration with some other backend system.

Thanks!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest!

You can use Google Colab to run our Retinexformer.

https://colab.research.google.com/

If your find our repo useful, please help us star it. Thanks :)
