### ISSUE TITLE
result on MIT 5k

### ISSUE THREAD

**Issue by AAAeray** [caiyuanhao1998/Retinexformer#142]
您好：
请问您还保留其他方法（DeepUPE [49] MIRNet [61] SNR-Net [57] Restormer [60]）在MIT 5k上的测试结果或者相关模型吗，例如SNRNet,我尝试利用他们的官方代码在你们提供的MIT数据集上训练，但是他们的代码不支持不同尺寸的数据，复现起来很麻烦。如果您保留了相关数据，将对我有很大帮助.
非常感谢

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，目前能找到的其他对比方法的结果在这里：
https://drive.google.com/drive/folders/1P75bv6jBp8UxcLDhqMACvIQXck2sS9da

对于不同尺寸的数据，采用我们 dataloader 里面的 crop patch 函数即可

如果你觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢 :)
