### ISSUE TITLE
运行test_from_dataset.py时报错

### ISSUE THREAD

**Issue by ChenConnie** [caiyuanhao1998/Retinexformer#143]
raceback (most recent call last):
  File "/home/cl/Desktop/workspace/Retinexformer/test_from_dataset.py", line 26, in <module>
    from basicsr.models import create_model
ImportError: cannot import name 'create_model' from 'basicsr.models' (/home/cl/anaconda3/envs/retinexformer/lib/python3.9/site-packages/basicsr/models/__init__.py)
作者你好，请问在运行test_from_dataset.py报错，怎么解决？

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

It seems that you did not install the basicsr successfully or you did not set the environment path right. Please check.

By the way, I also check the create model function in the __init__.py. It looks good:

https://github.com/caiyuanhao1998/Retinexformer/blob/master/basicsr/models/__init__.py#L21

**Comment by Drinking-4L** [comment]
我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model,取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。

**Comment by caiyuanhao1998** [comment]
感谢说明，我把这个 issue 给 pin 起来，让更多人看到

**Comment by zhangjy328** [comment]
> 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model,取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。

作者项目中也没有creat_model啊
![4778ceee-67b1-49ba-ac83-4ab296bfe65d](https://github.com/user-attachments/assets/dc465890-1794-4722-9014-922f32a3b713)

**Comment by zhangjy328** [comment]
> 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model,取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。
skimage中也没有img_as_ubyte，这个你遇到了吗？
![cdfe6a00-15cf-46c7-b32f-bb1565efc908](https://github.com/user-attachments/assets/6a264bf2-c723-403f-852c-0260c95d3a9a)

**Comment by caiyuanhao1998** [comment]
如果 skimage 都无法导入的话，感觉就是你的包没有装对

**Comment by Sami-UlRehman** [comment]
@caiyuanhao1998  is it compulsory to install BasicSR , because I have Docker based image on online Server, so installing BasicSR is not possible for now.

**Comment by zhuohai2363** [comment]
> > 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model,取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。
> > skimage中也没有img_as_ubyte，这个你遇到了吗？
> > ![cdfe6a00-15cf-46c7-b32f-bb1565efc908](https://github.com/user-attachments/assets/6a264bf2-c723-403f-852c-0260c95d3a9a)

请问解决了嘛？？

**Comment by zhuohai2363** [comment]
> 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model，取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。

希望大佬们出一篇环境配置的博客嘛，在这个呆了四五天了，都出不来

**Comment by sunpeize** [comment]
> > 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model，取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。
> 
> 希望大佬们出一篇环境配置的博客嘛，在这个呆了四五天了，都出不来
我注意到你之前发的无法用官方命令安装basicsr包，你可以这样解决：首先去下载Basicsr源码—git clone https://github.com/xinntao/BasicSR.git，之后进入Basicsr目录进行编译—pip install -e.，编译好后就安装好了，后面你在运行测试命令时，需要将test_from_dataset.py文件里面的from basicsr.models import create_model里面create_model改成build_model，from basicsr.utils.options import dict2str, parse以及下面opt = parse(args.opt, is_train=False)里面的parse都改成parse_options（因为Basic源码里面定义的函数名就是build_model和parse_options），希望这些能为你提供帮助 :)

**Comment by sunpeize** [comment]
> > 我也发现了这个问题。最后发现是basicsr这个包里面已经没有creat_model，取而代之的是build_model。解决方法是将作者项目中的整个basicsr文件夹直接拷贝到conda环境的包文件下面，如anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models，最后成功运行。
> 
> 希望大佬们出一篇环境配置的博客嘛，在这个呆了四五天了，都出不来

你直接把basicsr这个文件夹复制一份，粘贴到anaconda3/envs/Retinexformer/lib/python3.9/site-packages（注意你的环境名称），希望可以帮助到你 :）

**Comment by leungzzz** [comment]
遇到了同样的问题，发现自己没有 Install BasicSR 导致的。

按照 README.md的指引，运行 `python setup.py develop --no_cuda_ext` 后顺利运行。希望对后来者有帮助。 @zhuohai2363

**Comment by Sami-UlRehman** [comment]
> > > I also found this issue. In the end, it was found that there was no creat_model in the BasicSR package, and it was replaced by build_model. The solution is to copy the entire basicsr folder in the author's project directly to the package file of the conda environment, such as anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/models, and finally run successfully.  There is no img_as_ubyte in skimage, have you encountered this?
> > > ![cdfe6a00-15cf-46c7-b32f-bb1565efc908](https://github.com/user-attachments/assets/6a264bf2-c723-403f-852c-0260c95d3a9a)
> 
> Is it solved? ?

if there is issue installing the BasicSR , you can simply add the path of you project folder like Retinexformer is the folder holding all the files, into train.py if you want to  retrain  or  test_from_dataset.py file if you want to test on the top of the respective file using os.path
