### ISSUE TITLE
yolo端到端训练

### ISSUE THREAD

**Issue by roemin1999** [caiyuanhao1998/Retinexformer#145]
您好，如果把该模块放到yolo网络里，训练出来的模型进行检测，结果图片和输入图片是一样的吗？如果是一样的我该怎么拿到中间低照度增强后的图片，期待您的回复

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。这么做的结果图片和输入图片是不一样的：
（1）结果图片对比输入低光图片，亮度会被增强
（2）结果图片上会有预测的检测框

**Comment by roemin1999** [comment]
> 你好，感谢关注。这么做的结果图片和输入图片是不一样的： （1）结果图片对比输入低光图片，亮度会被增强 （2）结果图片上会有预测的检测框
![1](https://github.com/user-attachments/assets/246868e9-965b-44d3-83d6-1b5d5f9cba94)
您好，但是我加入之后结果图片亮度没有增强，只是加了检测框，不过相对原来的模型对精度有变化

**Comment by roemin1999** [comment]
您好，但是我加入之后结果图片亮度没有增强，只是加了检测框，不过相对原来的模型对精度有变化
![1](https://github.com/user-attachments/assets/3fe5fdbd-339e-42ec-80f8-6c568931be7e)
