### ISSUE TITLE
LIME , NPE , MEF, DICM  and VV数据集的使用

### ISSUE THREAD

**Issue by climberwu** [caiyuanhao1998/Retinexformer#146]
你好，大佬，请问LIME , NPE , MEF, DICM  and VV数据集在提供的代码中是如何使用的呢？？？

**Comment by github010719** [comment]
我也想问，可以处理没有配对的图片吗，

**Comment by caiyuanhao1998** [comment]
你们好，感谢关注。

只需要在 config 里面修改 input 和 GT 的路径即可，全部修改为输入的五个数据集的低光图像的路径就好。我们同时也提供了我们方法在这五个数据集上的测试结果。请参考 `README.MD` 下载获取。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下吧，感谢 :)

**Comment by climberwu** [comment]
谢谢大佬，十分感谢

**Comment by climberwu** [comment]
你好大佬，请问，我将config的LOLv1.yml里面的
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
#    dataroot_gt: data/LOLv1/Train/target
#    dataroot_lq: data/LOLv1/Train/input
    dataroot_gt: data/DICM
    dataroot_lq: data/DICM
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk



  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/DICM
    dataroot_lq: data/DICM
    io_backend:
      type: disk



这个修改对不对呢，我修改之后，69个图要训练两天，是不是有点问题呢？

**Comment by climberwu** [comment]
你好大佬，请问，我将config的LOLv1.yml里面的
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
#    dataroot_gt: data/LOLv1/Train/target
#    dataroot_lq: data/LOLv1/Train/input
    dataroot_gt: data/DICM
    dataroot_lq: data/DICM
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk



  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/DICM
    dataroot_lq: data/DICM
    io_backend:
      type: disk



这个修改对不对呢，我修改之后，69个图要训练两天，是不是有点问题呢？
