### ISSUE TITLE
无GT数据的测试问题

### ISSUE THREAD

**Issue by Kittywyk** [caiyuanhao1998/Retinexformer#15]
您好，首先非常感谢您有意义的工作！我有几个问题想请教一下：
1. 请问LIME, NPE, MEF, DICM, 和VV这几个没有GT数据集的增强结果是使用哪个预训练参数预测得到的？
2. repo中是否有提供在自定义数据上直接进行测试的代码？ 
3. 如果在自己的数据上进行直接增强，推荐使用哪个预训练参数？
4. 按照您提供的tutorial，在ExDark上的训练需要使用IAT-Yolo的repo，我看了下貌似没有将Retinexformer集成进去，需要自定义添加对吗？
期待您的回复，非常感谢！

**Comment by caiyuanhao1998** [comment]
哈喽，感谢你的关注。

1. 这几个无监督数据集可以采用八个有GT数据集上训练得到表现较好的model去分别作测试，然后挑出视觉效果好的结果。建议用 LOL-v2-synthetic。

2. 可以直接把测试部分代码的路径指定到自己的数据集路径即可

3. 与第一个问题一样，建议都试一下，然后看视觉效果哪个好

4. 是的，需要自己加一下

如果觉得有帮助的话，帮忙点点 star 支持一下

**Comment by Kittywyk** [comment]
感谢您的回复！已star

**Comment by caiyuanhao1998** [comment]
> 感谢您的回复！已star

并没有哦，目前没看到哦

**Comment by Kittywyk** [comment]
哈哈好像漏点了，这次是真的已star了。
