### ISSUE TITLE
about ssim

### ISSUE THREAD

**Issue by MSL502** [caiyuanhao1998/Retinexformer#16]
Dear author：
     In train.py, I see that psnr is used when verifying the dataset and the best psnr model is saved, but when judging whether it is the optimal model, I do not see the ssim. Is it the best psnr model saved and the ssim tested with the best psnr model.
    I would appreciate a reply from the author.

Related code: 
 if best_metric['psnr'] < current_metric:
 best_metric['psnr'] = current_metric
  best_metric['iter'] = current_iter
  model.save_best(best_metric)

**Comment by caiyuanhao1998** [comment]
We save the model with the highest PSNR.
The SSIM is tested with the best PSNR model.

If you find our repo helpful, please help us star it. ⭐ 
Thanks.
