### ISSUE TITLE
关于SID数据集使用问题

### ISSUE THREAD

**Issue by MSL502** [caiyuanhao1998/Retinexformer#17]
尊敬的作者：
        您好，我看到代码RetinexFormer_SID.yml 中datasets 目录格式是这样子 dataroot_gt: data/SID/long_sid2，但是给出的SID数据集网盘都是一个文件夹一个文件夹（10003、10006），请问数据集应该怎么使用呢？

**Comment by caiyuanhao1998** [comment]
直接把链接中的整个sid下载下来，然后按照prepare dataset部分放置数据文件，然后用我们的训练测试代码就可以直接跑起来。config文件中会指定哪个编号的子文件夹会被用到。

如果感觉我们的repo有帮助的话，帮忙点点 star 🌟 支持一下，谢谢

**Comment by MSL502** [comment]
作者您好，
我已经把sid整个下载下来，但是Prepare Dataset中没有介绍关于SID数据文件放置的问题。请问在RetinexFormer_SID.yml中datasets中dataroot_gt和dataroot_lq分别应该怎么设置呀
