### ISSUE TITLE
关于消融实验

### ISSUE THREAD

**Issue by cjl506** [caiyuanhao1998/Retinexformer#18]
您好，想请问请问一下消融实验部分表4(a)中的Baseline-1具体成分是啥呢？希望被关注到这个问题,请回复一下,谢谢您!

**Comment by caiyuanhao1998** [comment]
如文中 4.4 章节所述，Baseline-1 是去掉了 ORF 和 IG-MSA后的网络部分。

如果感觉有帮助的话，帮忙点点star支持一下 🌟

**Comment by cjl506** [comment]
![图片](https://github.com/caiyuanhao1998/Retinexformer/assets/83258906/d814f5fa-c616-4e76-9a98-ea80d90239c5) 
非常抱歉在您的图上做了一个标注，您的意思就是去掉我用蓝色框标注的地方，剩下的成分用来端到端增强是吗？感谢您的回复，祝科研顺利！

**Comment by cjl506** [comment]
![图片](https://github.com/caiyuanhao1998/Retinexformer/assets/83258906/3120d70a-1451-4819-b46f-80c0e01cb174)
在您发表的文章12506页上，公式5附近，我看到您交代了ORF的的具体是由两部分构成，一部分是亮度编码器，一部分是降质重构器。说实话，我没有太理解去掉那一部分呢。是整个网路都被去掉了吗？

**Comment by caiyuanhao1998** [comment]
第一张图圈中的部分去掉，去掉的是亮度估计器。你的理解是对的。
