### ISSUE TITLE
where is the pretrained_weights folder?

### ISSUE THREAD

**Issue by zz1plu** [caiyuanhao1998/Retinexformer#2]
hello, thanks for your great work. 
I cannot find the `pretrained_weights` folder as you mentioned. Could your please tell me where it is?

**Comment by caiyuanhao1998** [comment]
hello, thanks for your interest~
github cannot upload an empty folder. 
So you need to build a `pretrained_weights` folder yourself.

**Comment by zz1plu** [comment]
thanks for your quick reply : )
