### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by GaoTianWL** [caiyuanhao1998/Retinexformer#21]
您好！麻烦问下您，在训练的时候，选用的模型是basicsr.models.archs.RetinexFormer_arch当中的RetinexFormer
还是别的模型

**Comment by caiyuanhao1998** [comment]
没错，就是选这个

如果感觉有帮助的话，帮忙点点star支持一下 🌟

**Comment by GaoTianWL** [comment]
# general settings
name: Enhancement_RetinexFormer_LOL_v1
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100
这个当中的model_type: ImageCleanModel  是什么作用呢，是基于这个模型改进的吗

**Comment by caiyuanhao1998** [comment]
这个是BasicSR框架的模型类别，image clean就表示把退化的图像 变得 clean，比如原先图像带噪声然后处理干净。这个框架中，这个模型类别就表示，最终不作尺度的变换，比如像超分那样上采样。

**Comment by studier111** [comment]
您好，感谢分享，那修改model_type的名字也可以吧，同时修改image restoration中的对应model type的名字，改完后可以进行训练，影响训练出的模型吗？

**Comment by studier111** [comment]
> 这个是BasicSR框架的模型类别，image clean就表示把退化的图像 变得 clean，比如原先图像带噪声然后处理干净。这个框架中，这个模型类别就表示，最终不作尺度的变换，比如像超分那样上采样。
您好，感谢分享，那修改model_type的名字也可以吧，同时修改image restoration中的对应model type的名字，改完后可以进行训练，影响训练出的模型吗？
