### ISSUE TITLE
Parameters and floating point operations

### ISSUE THREAD

**Issue by zzukong** [caiyuanhao1998/Retinexformer#23]
Hello, I noticed that you reported the model complexity in your paper. May I ask how large an image you based your results on for your calculations?

**Comment by caiyuanhao1998** [comment]
Hi, the evaluation size is `256x256x3`

We have provided the evaluation code of Params and FLOPS function `my_summary()` in `Enhancement/utils.py`. Please check the Testing part in the readme and use our function.

If you find our repo helpful, please help us to start it 🌟 
Many thanks
