### ISSUE TITLE
About kernel_size in Illumination_Estimator module.

### ISSUE THREAD

**Issue by xinzwang** [caiyuanhao1998/Retinexformer#24]
As mentioned in your paper, sec3.1, "a depth-wise separable conv 9x9 is adopted to model the interactions of regions with different lighting conditions to generate the light-up feature F_{lu}". However, in "basicsr/model/archs/RetinexFormer_arch.py", class Illumination_Estimator, the kernel_size of "self.depth_conv" is set to 5.

I am curious about this difference. 

Thank you !

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

5x5 is correct and 9x9 is a typo. I forgot to revise it. Sorry for confusing.

If you find our repo helpful, please help us star it 🌟 

Thanks.
