### ISSUE TITLE
What is the input of the model when training with Adobe5K dataset?

### ISSUE THREAD

**Issue by Kravrolens** [caiyuanhao1998/Retinexformer#25]
Hi, I would like to know what the input (low-light images) of the model is when training with the Adobe 5K dataset. Or how do you get the input images?

Looking forward to your early reply! THANKS!

**Comment by caiyuanhao1998** [comment]
Hi, the input of the model when training with Adobe 5K dataset is low-light images of 5K. The input images are obtained by exporting the raw images of 5K with the sRGB mode. 

Please read [this issue](https://github.com/nothinglo/Deep-Photo-Enhancer/issues/38) for more details

We also provide the exported RGB low-/normal-light image pairs in the [Baidu Disk](https://pan.baidu.com/s/1ajax7N9JmttTwY84-8URxA?pwd=cyh2) (code:cyh2) and [Google Drive](https://drive.google.com/file/d/11HEUmchFXyepI4v3dhjnDnmhW_DgwfRR/view?usp=sharing) for your convenience to download. Please feel free to check and use them.
