### ISSUE TITLE
关于EXDARK图像增强

### ISSUE THREAD

**Issue by PZDJL** [caiyuanhao1998/Retinexformer#27]
你好作者，能否开源一下关于exdark图像增强的配置代码及训练模型。我这边对比实验需要exdark增强后的结果，如果可以的话后期会在我们的工作里面对你们的进行引用。

**Comment by caiyuanhao1998** [comment]
用这个[代码](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection)

如果感觉有帮助的话，帮我们点点star支持一下

**Comment by PZDJL** [comment]
是的已star，我们已经从你分享的链接获得了一些其他方法增强exdark的数据，但是我们还是非常需要基于Retinexformer增强的exdark数据。如果可以的话，希望能得到你的帮助

**Comment by caiyuanhao1998** [comment]
增强的部分结果在readme里面有，其余的可以拿我分享的链接跑一下，我这边没有存，我记得一天就可以跑完了。

**Comment by lecomet** [comment]
@PZDJL 你好 请问你获得了exdark增强后的图片了吗
