### ISSUE TITLE
exdark检测

### ISSUE THREAD

**Issue by zsn1107** [caiyuanhao1998/Retinexformer#28]
感谢您的共工作，请问如何将该网络作为预处理模块加入yolov3进行低光照检测，是否能提供代码？

**Comment by caiyuanhao1998** [comment]
你好，请使用这个repo来跑exdark的实验：
https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection
记得换成我们的Retinexformer

如果觉得有帮助的话，麻烦帮我们点点star支持一下

**Comment by zsn1107** [comment]
> 你好，请使用这个repo来跑exdark的实验： https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection 记得换成我们的Retinexformer
> 
> 如果觉得有帮助的话，麻烦帮我们点点star支持一下

请问怎样输出利用Retinexformer增强后的exdark图片并进行检测呢？像您网盘中给出的那样。我利用IAT代码进行检测后输出的仍是未增强的检测结果。
