### ISSUE TITLE
咨询下训练问题

### ISSUE THREAD

**Issue by TBWSZZ** [caiyuanhao1998/Retinexformer#29]
您好，按照您的步骤配置的环境和代码train后达不到您的效果，是不是还应该进行调试其他一些参数？您方便跟我说下吗？谢谢。我train的psnr只能达到22.89

**Comment by caiyuanhao1998** [comment]
你好，我们提供了所有数据集上的训练日志以供调试：

 [Baidu Disk](https://pan.baidu.com/s/16NtLba_ANe3Vzji-eZ1xAA?pwd=cyh2) (code: `cyh2`) or [Google Drive](https://drive.google.com/drive/folders/1HU_wEn_95Hakxi_ze-pS6Htikmml5MTA?usp=sharing)

请在训练时保持与训练日志的配置一致
