### ISSUE TITLE
 Missing key(s) in state_dict: "body.0.estimator.conv1.weight", 

### ISSUE THREAD

**Issue by msk7131** [caiyuanhao1998/Retinexformer#3]
when test ,it occur  that   Missing key(s) in state_dict: "body.0.estimator.conv1.weight", 
RuntimeError: Error(s) in loading state_dict for RetinexFormer:
        Missing key(s) in state_dict: "body.0.estimator.conv1.weight", "body.0.estimator.conv1.bias", "body.0.estimator.depth_conv.weight", "body.0.estimator.depth_conv.bias", "body.0.estimator.conv2.weight", "body.0.estimator.conv2.bias", "body.0.denoiser.embedding.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.rescale", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_q.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_k.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_v.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.proj.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.proj.bias", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.pos_emb.0.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.pos_emb.2.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.0.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.2.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.4.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.norm.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.norm.bias", "body.0.denoiser.encoder_layers.0.1.weight", "body.0.denoiser.encoder_layers.0.2.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.rescale", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_q.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_k.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_v.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.proj.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.proj.bias", "body.0.denoiser.encoder_layers.1.0.blocks.0.0

**Comment by caiyuanhao1998** [comment]
hello, which weights did you load? We have not encountered such a problem.

**Comment by bianhao123** [comment]
hi, the reason may be that the keys are not specified. 
You can refer to [https://github.com/caiyuanhao1998/Retinexformer/blob/master/Enhancement/test_from_dataset.py#L74](https://github.com/caiyuanhao1998/Retinexformer/blob/master/Enhancement/test_from_dataset.py#L74)
The code of loading weights  is as follow:
```python
checkpoint = torch.load(weights_path)
model.load_state_dict(checkpoint['params'])
```

**Comment by msk7131** [comment]
at the beginning, i run the code Enhancement/test_from_dataset.py, it occurs  that cannot find  the key  'params'  in  the pretrained checkpoint.  Then ,I delete the the key  'params'  ,ie:
from model.load_state_dict(checkpoint['params'])   to  model.load_state_dict(checkpoint)

**Comment by bianhao123** [comment]
> at the beginning, i run the code Enhancement/test_from_dataset.py, it occurs that cannot find the key 'params' in the pretrained checkpoint. Then ,I delete the the key 'params' ,ie: from model.load_state_dict(checkpoint['params']) to model.load_state_dict(checkpoint)

Can you share the printed info of the checkpoint?

**Comment by msk7131** [comment]
Retinexformer-master]$ python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL_v1.pth --dataset LOL_v1
/home/wzl/anaconda3/envs/th18/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
Traceback (most recent call last):
  File "Enhancement/test_from_dataset.py", line 80, in <module>
    model_restoration.load_state_dict(checkpoint['params'], strict=False)
KeyError: 'params'

**Comment by msk7131** [comment]
$ python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL_v1.pth --dataset LOL_v1
/anaconda3/envs/th18/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
Traceback (most recent call last):
  File "Enhancement/test_from_dataset.py", line 80, in <module>
    model_restoration.load_state_dict(checkpoint['params'], strict=False)
KeyError: 'params'

**Comment by caiyuanhao1998** [comment]
did you revise our code? did you set up the experiment as we suggested in the introduction?

**Comment by bianhao123** [comment]
> File "Enhancement/test_from_dataset.py", line 80, in model_restoration.load_state_dict(checkpoint['params'], strict=False) KeyError: 'params'

print(checkpoint), check the meta information

**Comment by EthanLiang99** [comment]
same question here !! 
I think it is caused by the different names of keys,  expected module.body.0.estimator.conv1.weight but got body.0.estimator.conv1.weight from the check point.........

detail of error:
 Missing key(s) in state_dict: "module.body.0.estimator.conv1.weight", "module.body.0.estimator.conv1.bias", 
 Unexpected key(s) in state_dict: "body.0.estimator.conv1.weight", "body.0.estimator.conv1.bias", "body.0.estimator.depth_conv.weight",

**Comment by caiyuanhao1998** [comment]
It is weird because we re-installed the environment, tested again, and did not encounter this issue.
Did you set up the environment as we suggested in the introduction?

**Comment by caiyuanhao1998** [comment]
<img width="1018" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/48472661/8bffbc70-513f-4635-be2e-2315b15cc75a">

**Comment by linjing7** [comment]
@msk7131 @msk7131 I install the environment and package following the instructions. And then I can successfully test with the pretrained model and get the correct results:
<img width="1870" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/70081899/c5e33991-e4f1-499b-b084-1b4bbc34ad71">
<img width="1857" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/70081899/e1307cd6-af56-4950-a452-3a7af2de0b46">
<img width="1872" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/70081899/19981888-e0ca-431c-afd2-87a1c60eef77">

**Comment by caiyuanhao1998** [comment]
Hi, we fixed the bug by adding the following two lines of code to modify the dict structure:

<img width="567" alt="截屏2023-09-28 上午10 49 02" src="https://github.com/caiyuanhao1998/Retinexformer/assets/48472661/c255b99e-4202-4f84-8275-a2e1f4d7cab9">

Please try again. Good luck

**Comment by caiyuanhao1998** [comment]
sorry, we updated the loading script:

<img width="466" alt="截屏2023-09-28 上午11 04 37" src="https://github.com/caiyuanhao1998/Retinexformer/assets/48472661/d2af6966-9296-46bb-a5f6-38425fc66070">

Please try again. Good luck

**Comment by chaoyue12345678** [comment]
> File "Enhancement/test_from_dataset.py", line 80, in model_restoration.load_state_dict(checkpoint['params'], strict=False) KeyError: 'params'



> when test ,it occur that Missing key(s) in state_dict: "body.0.estimator.conv1.weight", RuntimeError: Error(s) in loading state_dict for RetinexFormer: Missing key(s) in state_dict: "body.0.estimator.conv1.weight", "body.0.estimator.conv1.bias", "body.0.estimator.depth_conv.weight", "body.0.estimator.depth_conv.bias", "body.0.estimator.conv2.weight", "body.0.estimator.conv2.bias", "body.0.denoiser.embedding.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.rescale", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_q.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_k.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.to_v.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.proj.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.proj.bias", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.pos_emb.0.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.0.pos_emb.2.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.0.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.2.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.fn.net.4.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.norm.weight", "body.0.denoiser.encoder_layers.0.0.blocks.0.1.norm.bias", "body.0.denoiser.encoder_layers.0.1.weight", "body.0.denoiser.encoder_layers.0.2.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.rescale", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_q.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_k.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.to_v.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.proj.weight", "body.0.denoiser.encoder_layers.1.0.blocks.0.0.proj.bias", "body.0.denoiser.encoder_layers.1.0.blocks.0.0

你好 你的这个问题解决了吗
