### ISSUE TITLE
检测

### ISSUE THREAD

**Issue by zsn1107** [caiyuanhao1998/Retinexformer#30]
![1](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/1b5fde12-56b6-485f-ae5f-b9d276802722)
请问如何得到这样的检测结果？我按照IAT的代码进行检测后图片还是低光照未增强的。
![图片2](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/325154a7-b921-4eb0-b84d-34c0cdc1a9fc)

**Comment by zsn1107** [comment]
那请问对exdark数据集低光增强的代码也是按照IAT中的来操作吗？将增强后的图片再运行img_demo进行检测？

**Comment by Jiafei127** [comment]
> 得先对低光图像进行增强，再进行目标检测

请问是对所有数据（包含训练集和测试集）进行增强后重新训练目标检测网络，还是只增强测试集，然后直接做检测呀？
