### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by zsn1107** [caiyuanhao1998/Retinexformer#31]
请问对没有gt的exdark数据集进行增强时，.yml文件路径应该如何更改呢？
![QQ图片20231129112508](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/3a32fce9-9220-4212-adb6-f19d58e14673)

**Comment by caiyuanhao1998** [comment]
你好，可以直接把 `dataroot_lq` 和  `dataroot_gt` 设置成一样，都是低光图片的路径
