### ISSUE TITLE
How to generate images of experimental results？

### ISSUE THREAD

**Issue by Zhouyang00** [caiyuanhao1998/Retinexformer#32]
Hi! I recently read your article and think it is an excellent  work! I trained the model with your code and measured SSIM using test_from_dataset.py, but I don't know how to generate images of experimental results?Thank you~

**Comment by caiyuanhao1998** [comment]
Thanks for your interest!

Hi, if you run `test_from_dataset.py`, the results will be saved in the folder `./results/`

If you find this repo helpful, please help us star it. Thanks

**Comment by xhlho** [comment]
你好，请问你解决了吗？我目前也是只有数值，但是无法出图

**Comment by bianhao123** [comment]
> 你好，请问你解决了吗？我目前也是只有数值，但是无法出图
请好，请检查一下保存图片的文件夹是否创建成功。可以试试打断电到保存图片处的代码，检查具体的保存路径和文件夹。

**Comment by xhlho** [comment]
好的，谢谢
