### ISSUE TITLE
Evaluating the Params and FLOPS of models

### ISSUE THREAD

**Issue by doctorzu** [caiyuanhao1998/Retinexformer#33]
作者你好。请问具体如何使用`from utils import my_summary
my_summary(RetinexFormer(), 256, 256, 3, 1)`它们应该放在哪里呢？

**Comment by caiyuanhao1998** [comment]
你好，我封装了函数 my_summary 来实现 evaluate Param and FLOPS 的功能。
readme 里面给出的这段是调用该函数的代码示例，你需要新建一个python脚本，把代码拷贝进去，调用 my_summary 函数来测试模型。
