### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by chaoyue12345678** [caiyuanhao1998/Retinexformer#35]
(chao) root@csim:~/home/lichaoyue/Retinexformer-master/basicsr# /root/anaconda3/envs/chao/bin/python /root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
Traceback (most recent call last):
  File "/root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py", line 78, in <module>
    model_restoration.load_state_dict(checkpoint['params'])
  File "/root/anaconda3/envs/chao/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RetinexFormer:
        Missing key(s) in state_dict: "body.0.estimator.channel_attention1.fc.0.weight", "body.0.estimator.channel_attention1.fc.0.bias", "body.0.estimator.channel_attention1.fc.2.weight", "body.0.estimator.channel_attention1.fc.2.bias", "body.0.estimator.channel_attention2.fc.0.weight", "body.0.estimator.channel_attention2.fc.0.bias", "body.0.estimator.channel_attention2.fc.2.weight", "body.0.estimator.channel_attention2.fc.2.bias". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py", line 83, in <module>
    model_restoration.load_state_dict(new_checkpoint)
  File "/root/anaconda3/envs/chao/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RetinexFormer:
        Missing key(s) in state_dict: "body.0.estimator.conv1.weight", "body.0.estimator.conv1.bias",
作者您好 很感谢您提供的代码 但我在测试中出现了这种原因 不知道怎么修改 也不清楚哪里出现错误了

**Comment by caiyuanhao1998** [comment]
Please refer to this [issue](https://github.com/caiyuanhao1998/Retinexformer/issues/3)

**Comment by chaoyue12345678** [comment]
for k in checkpoint [ 'params'] :

checkpoint [' params'] [k. replace(' .module', '')] = checkpoint['params'][k]  我看到了，但是这段代码不知道怎么加，下面是源代码，按照这个运行 还是有问题

checkpoint = torch.load(weights)
try:
    model_restoration.load_state_dict(checkpoint['params'])
except:
    new_checkpoint = {}
    for k in checkpoint['params']:
        #checkpoint [' params'] [k. replace(' .module', '')] = checkpoint['params'][k]
        new_key = k.replace(' .module', '')
        
        new_checkpoint['module.' + k] = checkpoint['params'][k]
    model_restoration.load_state_dict(new_checkpoint)

print("===>Testing using weights: ", weights)
model_restoration.cuda()
model_restoration = nn.DataParallel(model_restoration)
model_restoration.eval()

**Comment by caiyuanhao1998** [comment]
你的 num_gpu 设置成多少了？

**Comment by chaoyue12345678** [comment]
是在训练的时候吗 num_gpu=1 测试的时候 没有设置num_gpu

**Comment by chaoyue12345678** [comment]
Version Information: 
	BasicSR: 1.2.0+cc63400
	PyTorch: 1.13.1+cu117
	TorchVision: 0.14.1+cu117
2023-12-20 11:46:50,007 INFO: 
  name: RetinexFormer_LOL_v1
  model_type: ImageCleanModel
  scale: 1
  num_gpu: 1
  manual_seed: 100
  datasets:[
    train:[
      name: TrainSet
      type: Dataset_PairedImage
      dataroot_gt: data/LOLv1/Train/target
      dataroot_lq: data/LOLv1/Train/input
      geometric_augs: True
      filename_tmpl: {}
      io_backend:[
        type: disk
      ]
      use_shuffle: True
      num_worker_per_gpu: 8
      batch_size_per_gpu: 8
      mini_batch_sizes: [8]
      iters: [300000]
      gt_size: 128
      gt_sizes: [128]
      dataset_enlarge_ratio: 1
      prefetch_mode: None
      phase: train
      scale: 1      这是训练时候的配置

**Comment by chaoyue12345678** [comment]
parser = argparse.ArgumentParser(
    description='Image Enhancement using MIRNet-v2')

parser.add_argument('--input_dir', default='./Enhancement/Datasets',
                    type=str, help='Directory of validation images')
parser.add_argument('--result_dir', default='./results/',
                    type=str, help='Directory for results')
parser.add_argument(
    '--opt', type=str, default='/root/home/lichaoyue/Retinexformer-master/Options/RetinexFormer_SDSD_indoor.yml', help='Path to option YAML file.')
parser.add_argument('--weights', default='/root/home/lichaoyue/Retinexformer-master/pretrain_model/SDSD_indoor.pth',
                    type=str, help='Path to weights')
parser.add_argument('--dataset', default='SDSD_indoor', type=str,
                    help='Test Dataset') 
parser.add_argument('--gpus', type=str, default="0", help='GPU devices.')

args = parser.parse_args()

# 指定 gpu
gpu_list = ','.join(str(x) for x in args.gpus)
os.environ['CUDA_VISIBLE_DEVICES'] = gpu_list
print('export CUDA_VISIBLE_DEVICES=' + gpu_list)这是测试原本的代码 我将其这三行改了LOL_v1数据集，其他的都没改，这样做合适吗
parser.add_argument(
    '--opt', type=str, default='/root/home/lichaoyue/Retinexformer-master/Options/RetinexFormer_LOL_v1.yml', help='Path to option YAML file.')
parser.add_argument('--weights', default='/root/home/lichaoyue/Retinexformer-master/pretrain_model/LOL_v1.pth',
                    type=str, help='Path to weights')
parser.add_argument('--dataset', default='LOL_v1', type=str,

**Comment by chaoyue12345678** [comment]
(chao) root@csim:~/home# /root/anaconda3/envs/chao/bin/python /root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py
dataset LOL_v1
Traceback (most recent call last):
  File "/root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py", line 79, in <module>
    model_restoration.load_state_dict(checkpoint['params'])
  File "/root/anaconda3/envs/chao/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RetinexFormer:
        Missing key(s) in state_dict: "body.0.estimator.channel_attention1.fc.0.weight", "body.0.estimator.channel_attention1.fc.0.bias", "body.0.estimator.channel_attention1.fc.2.weight", "body.0.estimator.channel_attention1.fc.2.bias", "body.0.estimator.channel_attention2.fc.0.weight", "body.0.estimator.channel_attention2.fc.0.bias", "body.0.estimator.channel_attention2.fc.2.weight", "body.0.estimator.channel_attention2.fc.2.bias". 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py", line 87, in <module>
    model_restoration.load_state_dict(new_checkpoint)
  File "/root/anaconda3/envs/chao/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RetinexFormer: 还是出现这样的问题了

**Comment by caiyuanhao1998** [comment]
很奇怪，我这边直接测试没问题呀，你是下载的我们的 weights 来测试的吗？

**Comment by chaoyue12345678** [comment]
对的 就是在百度网盘下载的 pretrain_model 这个文件夹

**Comment by chaoyue12345678** [comment]
可以看一下你的test_from_dataset代码嘛 我看是我的测试代码不合适 还是测试数据集不合适

**Comment by caiyuanhao1998** [comment]
我就是用的这个 repo 里面的 test_from_dataset.py 代码

**Comment by chaoyue12345678** [comment]
(Retinexformer) root@csim:~/home# /root/anaconda3/envs/Retinexformer/bin/python /root/home/lichaoyue/Retinexformer-master/Enhancement/test_from_dataset.py
dataset LOLv1
===>Testing using weights:  /root/home/lichaoyue/Retinexformer-master/pretrain_model/LOL_v1.pth
data/LOLv1/Test/input
data/LOLv1/Test/target
0it [00:00, ?it/s]
/root/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/root/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
PSNR: nan 
SSIM: nan `现在出现了这种问题

**Comment by caiyuanhao1998** [comment]
你的数据路径搞错了，没有读取到图像

**Comment by chaoyue12345678** [comment]
您好，请问一下，您网络框架里面输入的图片，是那个数据集里面的图片，怎么没有找到 ，下面这张图









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月28日(星期四) 晚上11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [caiyuanhao1998/Retinexformer] 测试问题 (Issue #35)





 
你的数据路径搞错了，没有读取到图像

**Comment by 674123** [comment]
您好，我在运行测试的时候遇见了和您一样的问题，请问您解决了吗，困扰许久，还请解答：
(base) root@autodl-container-8a50119a52-09e6fee2:~/Retinexformer-master# python Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL.pth/net_g_1000.pth --dataset LOL_v1
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
Not using Automatic Mixed Precision
===>Testing using weights: pretrained_weights/LOL.pth/net_g_1000.pth
data/LOLv1/Test/input
data/LOLv1/Test/target
0it [00:00, ?it/s]
/root/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/root/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
PSNR: nan
SSIM: nan
