### ISSUE TITLE
你好，我这有一些小问题想询问下

### ISSUE THREAD

**Issue by xhlho** [caiyuanhao1998/Retinexformer#36]
首先非常感谢您的工作和开源代码，我目前已经复现了LOL_v1和LOL_v2两个，但是我目前有些疑问，我现在想将它使用到自定义数据集当中，但是我没有常规和阴暗两分类的数据，只有一份常规图像。我能否直接使用测试来对自定义数据集的图像进行亮度增强，我自己尝试了一些方法但是没成功，希望大佬帮帮忙，谢谢！

**Comment by caiyuanhao1998** [comment]
可以使用与 LOL_v1 相同的方式，用常规图像合成对应的阴暗图像（调低暗度，添加噪声），这样你就有了 常规-阴暗 图像对，用这些图像对来进行训练。

如果觉得有帮助的话，帮我们点点star支持一下

**Comment by xhlho** [comment]
我还想再了解下，是直接将合成的图像对使用 LOL_v1预训练模型进行测试然后得出光亮增强后的图像，还是需要先训练模型，再测试。希望大佬能回复下，谢谢！

**Comment by caiyuanhao1998** [comment]
都可以，后者效果会更好一些

**Comment by xhlho** [comment]
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/128131686/37727fa7-fbed-4e38-b73b-99e858391ff8)

**Comment by xhlho** [comment]
但是运行完在数据集里面会出现这个东西
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/128131686/ca89497e-fe52-4f05-b881-8bf03949a09c)
