### ISSUE TITLE
关于SDSD-indoor数据集划分的问题

### ISSUE THREAD

**Issue by GitKing-Wu** [caiyuanhao1998/Retinexformer#38]
首先，非常感谢您的工作与分享。

我通过您的代码，尝试对SDSD-indoor数据集进行划分，得到训练集图片：测试集图片=1655：308，我看您在论文中提到是62：6。

我的划分方法是将pair1、pair4、pair9、pair11、pair19、pair21以及他们的_2文件夹共12个文件夹划分测试集。

我想了解的是，我对SDSD数据集读取代码的理解是否存在问题？

非常感谢与期待您的回复。

**Comment by caiyuanhao1998** [comment]
可以拿我们的代码和预训练模型跑一下测试，如果指标对上的话，应该就没问题，以我们的代码为准
