### ISSUE TITLE
Ask about dataset about sid

### ISSUE THREAD

**Issue by YanJieWen** [caiyuanhao1998/Retinexformer#39]
I would like to ask about the data set SID, gtsize is defined as 256, but the read Dataset is [512,960] and gt_sizes is 256. Is the input gt_sizes defined in this way invalid? The size of the input network is 512,960. This is for a single block. Is the GPU taxing too much? Or the picture has been scaled somewhere in the code, and I hope the author will point it out. Thanks~

**Comment by caiyuanhao1998** [comment]
we crop patches of 256x256 during training to save the computational costs. In the testing phase, we use the whole image with its original size.

If you find our repo helpful, please help us star it.

Thanks.
