### ISSUE TITLE
256\times256 about sid datasets

### ISSUE THREAD

**Issue by YanJieWen** [caiyuanhao1998/Retinexformer#40]
Thank you for your reply. I have already stared your amazing work. But I checked all the codes and didn't find that it was cropped to 256*256 during the training phase. Can you tell me which module this operation occurs in?

**Comment by caiyuanhao1998** [comment]
Sorry, I misread, I thought you were talking about SDSD dataset.
For the SID dataset, we keep its original size [512, 960] during training. The setting of size [256, 256] in the config file is not used. I suggest you use A100 (80G) to train on the SID dataset to reproduce our results. Thanks.
