### ISSUE TITLE
the number of the IGAB blocks used in upsampling branch

### ISSUE THREAD

**Issue by nancy-ux** [caiyuanhao1998/Retinexformer#41]
Hi! I recently read the article and really appreciate your work.
But I noticed that in your article **Figure2(a)**, there are two IGAB blocks in the last step of upsampling branch when you get the F_0', but in your code, you only have one IGAB block. Can you please clarify this for me? Is there some mistake in the Figure2(a)？

**Comment by caiyuanhao1998** [comment]
Yes, that is a mistake in figure 2. Thanks for pointing out.
