### ISSUE TITLE
LR Schedule

### ISSUE THREAD

**Issue by eduardzamfir** [caiyuanhao1998/Retinexformer#44]
Hello, 

thanks for this nice work!

I have a question regarding the LR schedule. I've noticed differences between the descriptions outlined in the paper and the settings in the actual configuration file (specifically for RetinexFormer on the LoLv2-real dataset). You are also using larger crops than for the other datasets. Could you kindly provide some insight into the reasoning behind these differences?

Best,
Eduard

**Comment by caiyuanhao1998** [comment]
The illumination changes within a single image in this dataset are relatively large.
A larger receptive field is needed for the network to learn this illumination information.
Thus, we use a larger crop size.
