### ISSUE TITLE
我想向您了解一下use GT mean具体代表什么吗

### ISSUE THREAD

**Issue by zczs66** [caiyuanhao1998/Retinexformer#45]
2023.11.03 : The test setting of KinD, LLFlow, and recent diffusion models and the corresponding results on LOL are provided. Please note that we do not suggest this test setting because it uses the mean of the ground truth to obtain better results. But, if you want to follow KinD, LLFlow, and recent diffusion-based works for fair comparison, it is your choice to use this test setting. Please refer to the Testing part for details.
这里提到了使用相同的测试方式，我想问下这个具体的测试方式是指什么，有些不太理解

**Comment by caiyuanhao1998** [comment]
你好，就是把增强后的图像的均值调整到gt的均值后再算 PSNR 和 SSIM

```python
if args.GT_mean:
  # This test setting is the same as KinD, LLFlow, and recent diffusion models
  # Please refer to Line 73 (https://github.com/zhangyhuaee/KinD/blob/master/evaluate_LOLdataset.py)
  mean_restored = cv2.cvtColor(restored.astype(np.float32), cv2.COLOR_BGR2GRAY).mean()
  mean_target = cv2.cvtColor(target.astype(np.float32), cv2.COLOR_BGR2GRAY).mean()
  restored = np.clip(restored * (mean_target / mean_restored), 0, 1)
```

这种做法不正规，不专业，不建议采用。但是现在的一些方法在用，所以我们也提供这种 test setting 供大家选择。
