### ISSUE TITLE
how to train with multi gpus?

### ISSUE THREAD

**Issue by DL-Practise** [caiyuanhao1998/Retinexformer#46]

**Comment by caiyuanhao1998** [comment]
I have not tried multi-gpu training since our Retinexformer is very efficient and compact.

Yet, you can develop multi-gpu training by modifying the hyperparameter `--gpu_id` in `train.py` and the `gpu_num` in the config file.

**Comment by caiyuanhao1998** [comment]
If you find our repo helpful, please help us star it. Thanks
