### ISSUE TITLE
the test_list.txt for SDSD  dataset

### ISSUE THREAD

**Issue by nancy-ux** [caiyuanhao1998/Retinexformer#47]
Thank u for your work. I am very interested in it. I want to know how u choose the test dataset. Can I get the test_list.txt for SDSD  dataset? Thank u very much.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. We follow [SNR-Net](https://github.com/dvlab-research/SNR-Aware-Low-Light-Enhance) to select the test dataset. We do organize the test list but I believe you can easily organize them through the folder list in the config file :)

**Comment by nancy-ux** [comment]
I figure it out with your help. Thank u very much :)

**Comment by gejutaixiao22** [comment]
Hello, I have the same problem and I would like to ask how you solved it。Thank you very much。

**Comment by nancy-ux** [comment]
SDSD-indoor test：pair11,pair21,pair1,pair19,pair4,pair9
SDSD-outdoor test : MVI_0898,MVI_0928,MVI_0906,MVI_0975,MVI_1001,MVI_0997,MVI_1003,MVI_1026,MVI_1030,MVI_1032
