### ISSUE TITLE
RTX4090上720P单帧耗时120ms

### ISSUE THREAD

**Issue by wuhongsheng** [caiyuanhao1998/Retinexformer#48]
有没有什么模型推理加速方案或者工作

**Comment by caiyuanhao1998** [comment]
把图像尺寸变小，或者在训练时把模型的深度变小，原先是的 block 是 [1, 2, 2]，可以考虑改成 [1, 1, 1]

如果觉得我们的 repo 有帮助的话，帮忙点点 star 支持一下，感谢
