### ISSUE TITLE
visual results of other methods

### ISSUE THREAD

**Issue by Arusa1** [caiyuanhao1998/Retinexformer#49]
Thanks for your great work!

Could please share the visual results of other methods (such as Restormer, MIRNet, KinD) trained on corresponding datasets? A lot of methods did not provide pretrain weights on various datasets (such as lolv2real, lolv2synthetic, MIT Adobe FiveK). So it is time-comsuming to train their models from the scratch. It would be great if you are willing to share these visual results or pretrained weights.

Thanks anyway.

**Comment by caiyuanhao1998** [comment]
Unfortunately, we did not save these results.
