### ISSUE TITLE
Request for Preprocessing Code for SID 

### ISSUE THREAD

**Issue by 77885566** [caiyuanhao1998/Retinexformer#50]
I’m working with the SID dataset. Could you please share the preprocessing code or relevant resources to get the "sid_processed "dataset?

**Comment by caiyuanhao1998** [comment]
I did not preprocess this dataset myself. Please contact the authors of the SID dataset.

[Learning to see in the dark](http://openaccess.thecvf.com/content_cvpr_2018/html/Chen_Learning_to_See_CVPR_2018_paper.html)

If you find our repo useful, please help us star it.

**Comment by 77885566** [comment]
@caiyuanhao1998 In the SID public dataset(https://github.com/cchen156/Learning-to-See-in-the-Dark), the author did not process it into ‘npy’ format.  Could you please tell me how do you obtain the ‘npy‘ file ?

**Comment by caiyuanhao1998** [comment]
I did not process this dataset. I download the dataset from the [SNR-Net repo](https://github.com/dvlab-research/SNR-Aware-Low-Light-Enhance)
