### ISSUE TITLE
如何使用不成对的数据进行增强测试？How to test the performance with unpaired images?

### ISSUE THREAD

**Issue by SuGar123233** [caiyuanhao1998/Retinexformer#51]
项目内是否内置了使用不成对数据集进行测试/推理的函数接口？
Is there a built-in functional interface for testing/inference using unpaired datasets in this project?

**Comment by caiyuanhao1998** [comment]
测试的时候把 val 里面的 gt 和 input 的路径改成一样即可

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下

谢谢
