### ISSUE TITLE
关于basicsr模块

### ISSUE THREAD

**Issue by chaoyue12345678** [caiyuanhao1998/Retinexformer#52]
您好作者，麻烦打扰一下 关于basicsr模块 是直接用pip install basicsr 这种形势下载 还是根据git clone https://github.com/xinntao/BasicSR.git 这种先克隆 在下载

**Comment by caiyuanhao1998** [comment]
如果是直接使用 basicsr 的话，可以按照他的说明来下载

如果是使用我们的repo的话，就按照我们的 introduction 来安装

**Comment by chaoyue12345678** [comment]
谢谢了，刚试了一下，下载成功了，您好，再次打扰您一下，怎么可以保存illu_fea, illu_map，这两个中间结果图，试了好几次，保存的时候出现了错误，在代码Illumination_Estimator(nn.Module):模型中保存，还是在class RetinexFormer_Single_Stage(nn.Module):中添加代码，进行保存，保存的格式是怎的，麻烦作者了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caiyuanhao1998/Retinexformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月22日(星期五) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caiyuanhao1998/Retinexformer] 关于basicsr模块 (Issue #52)





 
如果是直接使用 basicsr 的话，可以按照他的说明来下载
 
如果是使用我们的repo的话，就按照我们的 introduction 来安装
