### ISSUE TITLE
关于LIME、NPE 、MEF 、DICM  和 VV数据集的测试

### ISSUE THREAD

**Issue by Dyf-hue** [caiyuanhao1998/Retinexformer#53]
您好！论文中提出对五个无gt图的数据集进行了测试，请问retinexformer不是有监督模型吗？是用别的配对数据集训练过的模型对这五个数据集进行测试的？还是使用了什么其他方法？ 此外，我对论文中对loss的描述比较意外，看过代码应该是论文中写错了？希望您看到后能解答我的疑惑，谢谢！

**Comment by yiguangke** [comment]
> 您好！论文中提出对五个无gt图的数据集进行了测试，请问retinexformer不是有监督模型吗？是用别的配对数据集训练过的模型对这五个数据集进行测试的？还是使用了什么其他方法？ 此外，我对论文中对loss的描述比较意外，看过代码应该是论文中写错了？希望您看到后能解答我的疑惑，谢谢！

您好，抱歉无法解决您的问题，想问问大佬怎么用这里面训练好的模型去测试我的低照度图像？

**Comment by Dyf-hue** [comment]
> > 您好！论文中提出对五个无gt图的数据集进行了测试，请问retinexformer不是有监督模型吗？是用别的配对数据集训练过的模型对这五个数据集进行测试的？还是使用了什么其他方法？ 此外，我对论文中对loss的描述比较意外，看过代码应该是论文中写错了？希望您看到后能解答我的疑惑，谢谢！
> 
> 您好，抱歉无法解决您的问题，想问问大佬怎么用这里面训练好的模型去测试我的低照度图像？

直接把配置文件中的测试数据集路径改为自己的数据集路径就行了，可是，不是同一个数据集训练出来的，效果应该不好

**Comment by yiguangke** [comment]
> > > 您好！论文中提出对五个无gt图的数据集进行了测试，请问retinexformer不是有监督模型吗？是用别的配对数据集训练过的模型对这五个数据集进行测试的？还是使用了什么其他方法？ 此外，我对论文中对loss的描述比较意外，看过代码应该是论文中写错了？希望您看到后能解答我的疑惑，谢谢！
> > 
> > 
> > 您好，抱歉无法解决您的问题，想问问大佬怎么用这里面训练好的模型去测试我的低照度图像？
> 
> 直接把配置文件中的测试数据集路径改为自己的数据集路径就行了，可是，不是同一个数据集训练出来的，效果应该不好

大佬能留个qq吗，最近搞毕设我有很多问题想问，有偿=~=

**Comment by caiyuanhao1998** [comment]
> 您好！论文中提出对五个无gt图的数据集进行了测试，请问retinexformer不是有监督模型吗？是用别的配对数据集训练过的模型对这五个数据集进行测试的？还是使用了什么其他方法？ 此外，我对论文中对loss的描述比较意外，看过代码应该是论文中写错了？希望您看到后能解答我的疑惑，谢谢！

用LOL和SMID训出来的模型去挨个试试，挑出效果好的就行。loss是enhanced image和gt image之间的Mean Absolute Error

**Comment by sukaixiong** [comment]
python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v2_real.yml --weights pretrained_weights/LOL_v2_real.pth --dataset VV
export CUDA_VISIBLE_DEVICES=0
dataset VV
Not using Automatic Mixed Precision
===>Testing using weights:  pretrained_weights/LOL_v2_real.pth
data/LOLv2/Real_captured/Test/Low
data/LOLv2/Real_captured/Test/Normal
0it [00:00, ?it/s]
/home/robot/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/robot/anaconda3/envs/Retinexformer/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
PSNR: nan 
SSIM: nan 
这种错误是为什么呢？
