### ISSUE TITLE
关于SSIM

### ISSUE THREAD

**Issue by Lost-Sunset** [caiyuanhao1998/Retinexformer#54]
（初学者同时也在研究毕设）运行了代码输出了psnr，如果想要获取或者输出SSIM该如何改动代码？
相关代码1：
                if best_metric['psnr'] < current_metric:
                    best_metric['psnr'] = current_metric
                    # save best model
                    best_metric['iter'] = current_iter
                    model.save_best(best_metric)
相关代码2：
        best_metric = resume_state['best_metric']
        best_psnr = best_metric['psnr']
        best_iter = best_metric['iter']
        logger.info(f'best psnr: {best_psnr} from iteration {best_iter}')

**Comment by caiyuanhao1998** [comment]
Enhancement/test_from_dataset.py 里面有测SSIM的代码和已经封装好的函数，请参照那边

**Comment by LuckyBoySSS** [comment]
<img width="1029" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/167675447/740f7d07-4ba6-4470-9586-f39fe4f33883">
<img width="546" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/167675447/ada1d469-baba-4e93-9778-848221f85674">

因为注意到模型最终PSNR相比论文报的结果有0.6db的GAP

想了解根据test set选取最佳模型的方法是否专业？
