### ISSUE TITLE
KeyError:'best_metric'

### ISSUE THREAD

**Issue by liliang2655** [caiyuanhao1998/Retinexformer#55]
![QQ图片20240326120926](https://github.com/caiyuanhao1998/Retinexformer/assets/164995245/f13cc2a2-9ef2-40b6-9101-853d58eed313)
大佬您好，请教一下这个是什么原因，我是按照您的readme写的，想训练 LOL-v1
conda activate Retinexformer
python3 basicsr/train.py --opt Options/RetinexFormer_LOL_v1.yml
然后就出现这个报错，请问是源码的问题还是我的配置有问题，求指点，感谢！

用您训练好的模型测试的时候都没问题
conda activate Retinexformer
python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL_v1.pth --dataset LOL_v1

**Comment by 5chen** [comment]
I have the same question. Have you fixed it ?

**Comment by liliang2655** [comment]
> 我有同样的问题。你修好了吗？

还没，在等作者大佬回复

**Comment by bianhao123** [comment]
> ![QQ图片20240326120926](https://private-user-images.githubusercontent.com/164995245/316759481-f13cc2a2-9ef2-40b6-9101-853d58eed313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ1ODksIm5iZiI6MTcxMTQ1NDI4OSwicGF0aCI6Ii8xNjQ5OTUyNDUvMzE2NzU5NDgxLWYxM2NjMmEyLTllZjItNDBiNi05MTAxLTg1M2Q1OGVlZDMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMTU4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWMxN2E3NTg0ZDdlNDhhNWJlMDg5YzZlYzJjYWJhMjkxZjlkN2ZiNzRjMTI2NzMxODVhMTRmMmI3MDU5ZDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKAXoFaymGTelIfyOmWxh-8vAhM47YKSewGpEGtCYcY) 大佬您好，请教一下这个是什么原因，我是按照您的readme写的，想训练 LOL-v1 conda activate Retinexformer python3 basicsr/train.py --opt Options/RetinexFormer_LOL_v1.yml 然后就出现这个报错，请问是源码的问题还是我的配置有问题，求指点，感谢！
> 
> 用您训练好的模型测试的时候都没问题 conda activate Retinexformer python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL_v1.pth --dataset LOL_v1

感谢您的关注，这个bug目前已经修复，请重新git pull一下仓库代码。

如果觉得了您的问题，帮忙点个star支持一下~

**Comment by bianhao123** [comment]
> I have the same question. Have you fixed it ?

Sorry, we have fixed this bug, please git pull the code.

If you find our repo helpful, please help us star it. Thanks

**Comment by liliang2655** [comment]
> > ![QQ图片20240326120926](https://private-user-images.githubusercontent.com/164995245/316759481-f13cc2a2-9ef2-40b6-9101-853d58eed313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ1ODksIm5iZiI6MTcxMTQ1NDI4OSwicGF0aCI6Ii8xNjQ5OTUyNDUvMzE2NzU5NDgxLWYxM2NjMmEyLTllZjItNDBiNi05MTAxLTg1M2Q1OGVlZDMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMTU4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWMxN2E3NTg0ZDdlNDhhNWJlMDg5YzZlYzJjYWJhMjkxZjlkN2ZiNzRjMTI2NzMxODVhMTRmMmI3MDU5ZDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKAXoFaymGTelIfyOmWxh-8vAhM47YKSewGpEGtCYcY) 大佬您好，请教一下这个是什么原因，我是按照您的readme写的，想训练 LOL-v1 conda activate Retinexformer python3 basicsr/train.py --opt Options/RetinexFormer_LOL_v1.yml 然后就出现这个报错，请问是源码的问题还是我的配置有问题，求指点，感谢！
> > 用您训练好的模型测试的时候都没问题 conda activate Retinexformer python3 Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL_v1.pth --dataset LOL_v1
> 
> 感谢您的关注，这个bug目前已经修复，请重新git pull一下仓库代码。
> 
> 如果觉得了您的问题，帮忙点个star支持一下~

感谢大佬，辛苦了，我再来试一下。
