### ISSUE TITLE
你好，谢谢您开源项目， 请问我在我电脑上nvidia3060上跑LOL-V1指标PSNR为22.92，SSIM为0.828，你的论文里面PSNR为25.16，SSIM为0.845，请问这个是什么原因，可以解答一下吗。

### ISSUE THREAD

**Issue by zgbuct** [caiyuanhao1998/Retinexformer#57]
你好，谢谢您开源项目，
请问我在我电脑上nvidia3060上跑LOL-V1指标PSNR为22.92，SSIM为0.828，你的论文里面PSNR为25.16，SSIM为0.845，请问这个是什么原因，可以解答一下吗。

**Comment by caiyuanhao1998** [comment]
请使用RTX8000，在我们指定的环境下跑，可以参考我们的 training log 来debug

**Comment by zgbuct** [comment]
这个不同硬件应该是没影响的
