### ISSUE TITLE
LOLv1 test

### ISSUE THREAD

**Issue by liliang2655** [caiyuanhao1998/Retinexformer#58]
![1566241170586580992](https://github.com/caiyuanhao1998/Retinexformer/assets/164995245/857d857a-93c8-4a31-b1d2-06e3dc7dbcda)
![1566241170586580992](https://github.com/caiyuanhao1998/Retinexformer/assets/164995245/5be4eea2-8ac7-43cc-bc67-a4772cc94ff7)
大佬您好，我尝试直接用您的LOLv1模型去处理我的数据，但是感觉效果很差，是不是我需要自行训练自己的模型，还是说我的原图片噪声太大了。求指点， 感谢！

**Comment by caiyuanhao1998** [comment]
哈喽, LOLv1 的模型直接处理你的数据，可能会有域差异。就是不同数据集训练出来的模型，泛化性都不一样。我的建议是你先用我们release的各种数据（我们开源了9个）上训练好的模型去分别测试，然后根据好的视觉效果来挑选增强后的图片。

当然，如果有条件的话，建议还是在自己的数据集上训练，这样子效果会好很多

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢

**Comment by rilixianren** [comment]
你好，怎么用已经训练好的模型LOL v1来处理自己的一张暗光图像呢
