### ISSUE TITLE
RetinexFormer_arch网络结构导入问题

### ISSUE THREAD

**Issue by thy0000** [caiyuanhao1998/Retinexformer#59]
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/51360380/7a4af5ed-d511-4ac5-804e-82451f93d78e)
作者大佬您好，我想请问一下，RetinexFormer_arch.py中的RetinexFormer网络结构是怎么导入到train.py中的呢？
在model/init.py文件中，我看到代码是通过扫描model文件夹下后缀为_model.py的文件进行动态导入，但在base_model.py和image_restoration_model.py中，我好像没有看到从RetinexFormer_arch.py中导入RetinexFormer网络结构的函数，请问一下是怎么导入的呢？请您解答我的疑惑，谢谢！

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，在 `basicsr/models/archs/__init__.py` 里面会注册并导入以 `__arch.py` 结尾的网络结构文件
