### ISSUE TITLE
训练细节请教

### ISSUE THREAD

**Issue by wajuda** [caiyuanhao1998/Retinexformer#61]
请问一下训练好的模型是怎么从训练结果中选出来的，和yml上的训练细节一致吗？复现的PSNR较预训练模型偏低
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/112617153/7784ce7a-db1a-4597-acd6-94c272b14df0)
上面是git上的模型，下面是自己训练的，选了不同epoch的结果也类似
谢谢解答

**Comment by wajuda** [comment]
刚才看了一下历史，发现也有几位遇到了同样的问题，查看了log也是相同的设置

**Comment by caiyuanhao1998** [comment]
你好，请按照我们推荐的环境，在RTX8000上跑实验。我们公布了训练日志，请和训练日志中的配置对齐来debug。因为LOL_v1的训练集只有15张图片，训练过程中测试集的指标浮动比较大，建议多训几次。

如果我觉得我们的repo有用的话，帮我们点点star支持一下，感谢

**Comment by 66ling66** [comment]
请问3090跑不出这样的结果吗？我们跑了很多次也是才23分出头

**Comment by wajuda** [comment]
我是在A40跑的
