### ISSUE TITLE
Discrepancies from the paper

### ISSUE THREAD

**Issue by Maydaybye** [caiyuanhao1998/Retinexformer#62]
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/75834797/6d8b2a47-5741-485d-bb21-6ed584304dea)
The paper states that the input image and lighting prior should be concatenated.
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/75834797/394ec953-96c8-4221-a179-96666fcc1eb0)
But as shown in the figure, the code you provided does not connect the lighting prior. Why is there a discrepancy from the paper?

**Comment by caiyuanhao1998** [comment]
Hi, the lighting prior is in the illumination estimator

<img width="785" alt="截屏2024-04-18 下午11 28 08" src="https://github.com/caiyuanhao1998/Retinexformer/assets/48472661/79096398-0df8-46a9-a9f4-35a040d8a50c">

If you find this repo useful, please help us star it. Thanks

**Comment by Maydaybye** [comment]
Apologize for my careless. And thank you for you prompt response.

**Comment by caiyuanhao1998** [comment]
It's OK, never mind.

If you find this repo useful, please help us star it. Thanks

**Comment by ZziTaiLeo** [comment]
illumination prior 为什么是通过取rgb均值作为光照图。  如果直接用对应的灰度图作为光照图会有什么影响呢
