### ISSUE TITLE
根据测试集选取模型？

### ISSUE THREAD

**Issue by LuckyBoySSS** [caiyuanhao1998/Retinexformer#63]
<img width="1029" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/167675447/740f7d07-4ba6-4470-9586-f39fe4f33883">
<img width="546" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/167675447/ada1d469-baba-4e93-9778-848221f85674">

因为注意到模型最终PSNR相比论文报的结果有0.6db的GAP

想了解根据test set选取最佳模型的方法是否专业？

**Comment by caiyuanhao1998** [comment]
我的建议是按照我们的环境在 RTX8000 单卡上多训练几次，按照我们的log来debug

或者就是把存下来的 model 多测几个

如果觉得我们的 repo 有用的话，帮忙点点 star，感谢
