### ISSUE TITLE
How to infer 6000x4000 images?

### ISSUE THREAD

**Issue by Zhou-Yijie** [caiyuanhao1998/Retinexformer#65]
I tried to use Retinexformer model to infer one  6000x4000 image but got Out Of Memory (A100 40G). Could you share how to do 6000x4000 image inference? (maybe need crop?)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests,

My suggestion is:

(i) Use a GPU with 48G memory to execute our code to infer 6k x 4k images.

or

(ii) You can modify this part of code to split the image into three part:

<img width="667" alt="截屏2024-04-23 下午11 04 10" src="https://github.com/caiyuanhao1998/Retinexformer/assets/48472661/ce272512-425d-4f0b-83a9-e21eb25f824b">

**Comment by ZziTaiLeo** [comment]
你好，我的显卡是24g的3090，好奇这种分割为n part的方式即等同于下采样吗

**Comment by caiyuanhao1998** [comment]
可以这么理解，但又并不完全是，这种拆分方式能让最后平凑的图片没有明显的明暗边界，语义上更为连续
