### ISSUE TITLE
关于SID Dataset

### ISSUE THREAD

**Issue by PikachuRX78** [caiyuanhao1998/Retinexformer#66]
作者您好
想要请教SID资料集的几件事

Config里面配置的pairXX是什么意思?
验证的时候是对整个Dataset进行验证吗?

另外想问Table 1上的其他模型的数据如果有原论文没跑的资料集是自己再跑的吗?
可否也提供那些模型的预训练权重?

**Comment by caiyuanhao1998** [comment]
你好，感谢关注

pair 表示 low-light / normal-light 训练数据对，表示不同的场景
验证的时候是对划分出来的验证集进行验证

对的，是自己再跑的
很抱歉，预训练权重在深圳的服务器上边，我现在在美国，无法access到那边。我后边会委托学弟帮忙找一下。其实自己训一下也挺简单的，直接把网络结构脚本文件拉到model下边注册即可跑了，用我们的codebase的话

感谢支持
