### ISSUE TITLE
您好，想向您请教一个问题

### ISSUE THREAD

**Issue by baijiesong** [caiyuanhao1998/Retinexformer#67]
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/105435837/dc9c55cd-dabe-4d05-959f-e5d5acd4e994)
大佬好，最近在复现大佬的工作，我是一名科研小白，想问问这种可视化的中间特征图是如何画出来的，在retinexformer_arch.py文件下实例化模型，加载训练权重，读入图片，在前向过程中保存下来这样嘛
期待您的回复~

**Comment by caiyuanhao1998** [comment]
同学你好，感谢你的关注

这是采用 opencv 的伪彩色图像，将单通道图变成RGB图

**Comment by baijiesong** [comment]
好滴我去学习一下，感谢感谢~
