### ISSUE TITLE
关于调用问题

### ISSUE THREAD

**Issue by huangyeye1** [caiyuanhao1998/Retinexformer#69]
您好，我想在别的python程序上调用训练好的模型，在安装好环境之后还是不能运行，请问想在别的python程序上调用该模型该怎么做

**Comment by caiyuanhao1998** [comment]
建议你在我们的程序上调用我们训练好的模型，不同程序之间的 codebase 和实现方式都有差别，容易报错。对初学者来说，还是一步步按顺序配环境，调用会保险一些。

如果觉得我们的repo有用的话，帮忙点点star支持一下，感谢
