### ISSUE TITLE
目标检测问题

### ISSUE THREAD

**Issue by ppp123dadsad** [caiyuanhao1998/Retinexformer#70]
您好，我想使用您的模型预处理图像，再使用yolov8进行目标检测，请问你们有这方面的代码吗，我在结合两部分代码的时候运行出了问题。

**Comment by caiyuanhao1998** [comment]
你可以看看 mmdetection 里面是否有 yolov8 的代码。或者你使用我们的模型对暗光图片进行前处理，存好后再训练也可以哦。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下
