### ISSUE TITLE
安装cudatoolkit=11.3失败

### ISSUE THREAD

**Issue by HCL0708** [caiyuanhao1998/Retinexformer#72]
我在安装cudatoolkit=11.3时出现了错误，我在不安装cudatoolkit=11.3的情况下，代码也可以正常运行，请问不安装cudatoolkit=11.3会怎么样

**Comment by caiyuanhao1998** [comment]
没有试过非 11.3 的，应该不会有啥问题吧，hhh~

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢
