### ISSUE TITLE
A question in IG-MSA

### ISSUE THREAD

**Issue by Maydaybye** [caiyuanhao1998/Retinexformer#73]
out_c = self.proj(x).view(b, h, w, c)
Why use view(b, h, w, c)? I tried it with a single image, and this operation reduces the resolution of the input image and duplicates it several times.
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/75834797/baf5d09a-31c6-4868-bd3d-521d812e683e)
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/75834797/1f9e10af-1e3b-46e8-867d-2280d17a7b54)

**Comment by caiyuanhao1998** [comment]
What do you mean by " tried it with a single image"

What did you try? A projection layer, an MSA, or a Retinexformer?

**Comment by caiyuanhao1998** [comment]
if you find our repo useful, please help us star it
