### ISSUE TITLE
分布式训练问题

### ISSUE THREAD

**Issue by 348330** [caiyuanhao1998/Retinexformer#74]
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/166403807/5d90e419-4c78-460e-841c-8f60e288131c)
作者您好，我想请教一下模型如何进行分布式训练？以及如果我有两个GPU，分别是GPU0和GPU1，如何设置模型只在GPU1上运行?谢谢！

**Comment by caiyuanhao1998** [comment]
请按照我们的 readme 里面的介绍配置环境并执行命令进行分布式训练。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下
