### ISSUE TITLE
basicsr安装问题

### ISSUE THREAD

**Issue by IKnowWhoo** [caiyuanhao1998/Retinexformer#76]
作者你好，服务器位于内网无法使用setup.py安装,只能外网打包环境传进去。使用pip安装basicsr迁移到内网，运行时报错  `python Enhancement/test_from_dataset.py --opt Options/RetinexFormer_NTIRE.yml --weights pretrained_weights/NTIRE.pth --dataset NTIRE --self_ensemble                Traceback (most recent call last):                                                                                        File "/mnt/d/Workspace/Retinexformer-master/Enhancement/test_from_dataset.py", line 26, in <module>                       from basicsr.models import create_model                                                                               File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/__init__.py", line 4, in <module>       from .data import *                                                                                                   File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/data/__init__.py", line 22, in <module>                                                                                                                         _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]          File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/data/__init__.py", line 22, in <listcomp>                                                                                                                       _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]          File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/importlib/__init__.py", line 127, in import_module            return _bootstrap._gcd_import(name[level:], package, level)                                                           File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>                                                                                                               from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels                                   File "/home/anne/anaconda3/envs/Retinexformer/lib/python3.9/site-packages/basicsr/data/degradations.py", line 8, in <module>                                                                                                                      from torchvision.transforms.functional_tensor import rgb_to_grayscale                                               ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor' `
外网使用setup.py安装可以正常运行。尝试pip安装basicsr 1.2.0+cc63400迁移到内网也失败了，报错没有该版本。
`$ conda list basicsr
packages in environment at /home/anne/anaconda3/envs/Retinexformer:
Name                    Version                   Build  Channel
basicsr                   1.2.0+cc63400             dev_0    <develop>`  请问有什么解决方案吗？

**Comment by caiyuanhao1998** [comment]
你好，感谢你的关注。我的建议是找管理员修改网络让服务器能够连接外网。因为跑实验需要安装很多包，如果服务器没有联网的话，conda环境的安装或者 pip install 都没法进行，会产生很多bug。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下
