### ISSUE TITLE
照度推导问题

### ISSUE THREAD

**Issue by Ambitionfy** [caiyuanhao1998/Retinexformer#77]
你好，请问在你的论文Eq. 3中，满足的条件是\bar{L} \odot L = 1, 但是这个约束是如何在网络中体现出的呢？我似乎没有看到有关\bar{L}的约束

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。是这样的，因为如果拟合辐照度图 L 的话，后续变换就需要涉及除法，而除法操作对计算机很不友好，容易导致数值溢出问题。因此，我们直接拟合 L 的倒数，在后续操作中就做乘法，让训练更稳定一些。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下，感谢

**Comment by Ambitionfy** [comment]
> 好，谢谢关注。是这样的，因为如果拟合辐照度图 L 的话，后续变换就需要涉及除法，而除法操作对计算机很不友好，容易导致数值溢出问题。因此，我们直接拟合 L 的倒数，在后续操作中就做乘法，让训练更稳定一些。
> 
> 如果觉得我们的repo有用的话，帮忙点点star支持一下，谢谢

你好，感谢你的回复。但是在你的网络里，如何保证学习到的是1./L呢？因为我没有看到对其有关的约束，只是看到I与学习到的特征进行相乘。
