### ISSUE TITLE
ProRGB input files? FiveK model

### ISSUE THREAD

**Issue by zelenooki87** [caiyuanhao1998/Retinexformer#79]
Hi.
I saw that fivek enhancement models better perform on prorgb format.
By prorgb, does it means ProPhoto RGB?
Because I have tested some Prophoto pngs, and output is darker and not better than sRGB.
https://paperswithcode.com/sota/image-enhancement-on-mit-adobe-5k?p=retinexformer-one-stage-retinex-based
Thank you very much

**Comment by caiyuanhao1998** [comment]
hi, thanks for your interests.

ProRGB means the ProPhoto RGB color space. It is a specific type of RGB color space developed by Kodak. This color space is designed for high-end image editing with a very wide gamut, suitable for professional photography to ensure colors are reproduced faithfully in digital editing environments.

If you find our repo useful. Please help us star it. Thanks.

**Comment by zelenooki87** [comment]
Why you immediately close issue?
Yeah, I know that Fact for ProPhoto RGB. I exported raw files in Photoshop to ProPhoto tiff. But tiff files seems unsupported so I have changed extension to png and retinexformer work but not as expected. 
Could you give instructions how to test in Prophoto RGB mode'
Thanks

**Comment by caiyuanhao1998** [comment]
this repo does not have pretrained weights for proRGB. if you want to do experiments on prorgb，i suggest you firstly output the image，and then train the model on the output images.

**Comment by zelenooki87** [comment]
could you share proRGB weights?
BTW, I am already blown up with srgb model but it would be interesting to share weights.
Cause I am not familiar with training.
Thank you very much

**Comment by caiyuanhao1998** [comment]
hi, I have not done the experiment of proRGB. I do not suggest you to use proRGB. It is not friendly for human eyes. Srgb is better.
