### ISSUE TITLE
我从你们提供的百度盘下载了SMID和SDSD-indoor数据，都不能正常解压

### ISSUE THREAD

**Issue by ZHangtao199311** [caiyuanhao1998/Retinexformer#8]

**Comment by caiyuanhao1998** [comment]
这两个链接都是官方提供的

SMID: seeing motion in the dark
https://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Seeing_Motion_in_the_Dark_ICCV_2019_paper.pdf

SDSD: https://github.com/dvlab-research/sdsd
[Seeing Dynamic Scene in the Dark: High-Quality Video Dataset with Mechatronic Alignment](https://github.com/dvlab-research/sdsd#seeing-dynamic-scene-in-the-dark-high-quality-video-dataset-with-mechatronic-alignment)

没法正常解压是遇到什么问题了？

google drive 下载的可以解压吗？

**Comment by ZHangtao199311** [comment]
解压直接提示error
好的，我再试试google的
谢谢
------------------------------------------------------------------
发件人：Yuanhao Cai ***@***.***>
发送时间：2023年9月28日(星期四) 21:40
收件人：caiyuanhao1998/Retinexformer ***@***.***>
抄　送： 张涛 ***@***.***>; Author ***@***.***>
主　题：Re: [caiyuanhao1998/Retinexformer] 我从你们提供的百度盘下载了SMID和SDSD-indoor数据，都不能正常解压 (Issue #8)
这两个链接都是官方提供的
SMID: seeing motion in the dark
https://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Seeing_Motion_in_the_Dark_ICCV_2019_paper.pdf <https://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Seeing_Motion_in_the_Dark_ICCV_2019_paper.pdf >
SDSD: https://github.com/dvlab-research/sdsd <https://github.com/dvlab-research/sdsd >
Seeing Dynamic Scene in the Dark: High-Quality Video Dataset with Mechatronic Alignment <https://github.com/dvlab-research/sdsd#seeing-dynamic-scene-in-the-dark-high-quality-video-dataset-with-mechatronic-alignment >
没法正常解压是遇到什么问题了？
google drive 下载的可以解压吗？

**Comment by ZHangtao199311** [comment]
我从谷歌下载了indoor_static_np.zip解压的时候还是出错, 
unzip indoor_static_np.zip
出错:
Archive: indoor_static_np.zip
warning [indoor_static_np.zip]: zipfile claims to be last disk of a multi-part archive;
 attempting to process anyway, assuming all parts have been concatenated
 together in order. Expect "errors" and warnings...true multi-part support
 doesn't exist yet (coming soon).
file #1: bad zipfile offset (local header sig): 4
file #2: bad zipfile offset (local header sig): 51
file #3: bad zipfile offset (local header sig): 101
file #4: bad zipfile offset (local header sig): 157
.
.
.
------------------------------------------------------------------
发件人：Yuanhao Cai ***@***.***>
发送时间：2023年9月29日(星期五) 03:12
收件人：caiyuanhao1998/Retinexformer ***@***.***>
抄　送： 张涛 ***@***.***>; Author ***@***.***>
主　题：Re: [caiyuanhao1998/Retinexformer] 我从你们提供的百度盘下载了SMID和SDSD-indoor数据，都不能正常解压 (Issue #8)
Closed #8 <https://github.com/caiyuanhao1998/Retinexformer/issues/8 > as completed.

**Comment by caiyuanhao1998** [comment]
SMID的谷歌链接时没问题的对吧。

OK，我现在下载SDSD解压试试看。

**Comment by ZHangtao199311** [comment]
您好，我没有去谷歌下载SMID了；
SDSD您这边下载的可以正常解压吗？
------------------------------------------------------------------
发件人：Yuanhao Cai ***@***.***>
发送时间：2023年9月29日(星期五) 10:50
收件人：caiyuanhao1998/Retinexformer ***@***.***>
抄　送： 张涛 ***@***.***>; Author ***@***.***>
主　题：Re: [caiyuanhao1998/Retinexformer] 我从你们提供的百度盘下载了SMID和SDSD-indoor数据，都不能正常解压 (Issue #8)
SMID的谷歌链接时没问题的对吧。
OK，我现在下载SDSD解压试试看。

**Comment by caiyuanhao1998** [comment]
我这边试了一下好像确实没法打开，好奇怪，我去年的时候还是可以的，我先把这个issue打开，等解决了再close

**Comment by bianhao123** [comment]
@ZHangtao199311 你好，可以使用bandzip进行解压缩（默认可以将.zip和.z01一块解压）
<img width="720" alt="image" src="https://github.com/caiyuanhao1998/Retinexformer/assets/33709251/4dbfdbcb-e2c8-4ba6-bc3b-a8952f5e075f">

**Comment by ZHangtao199311** [comment]
好的，谢谢
------------------------------------------------------------------
发件人：bianhao ***@***.***>
发送时间：2023年9月30日(星期六) 13:10
收件人：caiyuanhao1998/Retinexformer ***@***.***>
抄　送： 张涛 ***@***.***>; Mention ***@***.***>
主　题：Re: [caiyuanhao1998/Retinexformer] 我从你们提供的百度盘下载了SMID和SDSD-indoor数据，都不能正常解压 (Issue #8)
@ZHangtao199311 <https://github.com/ZHangtao199311 > 你好，可以使用bandzip进行解压缩（默认可以将.zip和.z01一块解压）
 <https://user-images.githubusercontent.com/33709251/271755060-4dbfdbcb-e2c8-4ba6-bc3b-a8952f5e075f.png >

**Comment by caiyuanhao1998** [comment]
如果觉得有帮助的话，帮忙点点star支持一下，谢谢~

**Comment by Black7769** [comment]
SMID 有分开的测试集吗 单独下载
