### ISSUE TITLE
大佬有无监督（没有配对数据）的方案么？

### ISSUE THREAD

**Issue by gjd2017** [caiyuanhao1998/Retinexformer#84]

**Comment by caiyuanhao1998** [comment]
hello，我们在五个没有配对数据集（LIME, NPE, MEF, DICM, and VV）上也测试了我们的算法，也提供了测试结果方便大家对比。

如果想应用到无监督方案的话，可以直接把无监督的范式用在整体的 Retinexformer 或者把我们的模块如 IGAB 或者 IG-MSA plug in 到一个无监督框架中

如果觉得我们的 repo 有用的话，求帮忙点点 star 支持一下，感谢 :)

**Comment by liuwanqingqing** [comment]
你好，可以举例一下使用无监督方法的情况吗
