### ISSUE TITLE
Information about training resources?

### ISSUE THREAD

**Issue by Koruvika** [caiyuanhao1998/Retinexformer#85]
Hi, I'm planning to retrain Retinexformer on my dataset, but I don't know your resources for training, how much VRAM used for training with configs in your paper?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interests.

I suggest you train our model on 3090 for fivek and lol-v2-real datasets and train on rtx 8000 for other datasets.

if you train our model at the spatial size of 256x256 like lol, fivek, sdsd, side. The memory usage would be 2-4 G

if you train our model at the spatial size of 960x512 like Sid the memory usage would be over 40 G.

if you train our model on the ntire datasets with our multi-gpu training and mixed-precision training. The VRAM is about 48 g

If you find our repo useful, please help us star it. Thank you.
