### ISSUE TITLE
输出通道数

### ISSUE THREAD

**Issue by zsn1107** [caiyuanhao1998/Retinexformer#86]
![`ZIKL04A`UI~15X`T}MU8MI](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/eabda7c7-bf0f-4510-9d8f-77c4f2da1d42)
请问这里的C是多少呢，代码中的n_feat为什么是31？有些没看懂

**Comment by caiyuanhao1998** [comment]
你好，感谢关注
对的，31，这就是个超参数，可以根据网络的参数量和计算量来进行调整和修改的

如果觉得我们的 repo 有用的话，帮忙 fork 支持一下，感谢！

**Comment by zsn1107** [comment]
> 你好，感谢关注 对的，31，这就是个超参数，可以根据网络的参数量和计算量来进行调整和修改的
> 
> 如果觉得我们的 repo 有用的话，帮忙 fork 支持一下，感谢！

![0~O@`GQG`RE@M~BT%PQXO0Y](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/882b4a60-8ce0-45cd-b04c-14d342d89323)
那这里的n_feat为什么输入40呢，我改成31的话就会报错
