### ISSUE TITLE
关于阶段数

### ISSUE THREAD

**Issue by ycwsilent** [caiyuanhao1998/Retinexformer#87]
您好，我注意到，您强调你们的网络是1阶段的；但是我下载代码来看的时候，发现3似乎是3个阶段的
![image](https://github.com/caiyuanhao1998/Retinexformer/assets/171780109/6f7c4851-7b79-403a-9c1c-a557e419eec7)
是我理解的不对吗，这个是3个您图中的网络吗，就是经过3次增强来实现的吗

**Comment by caiyuanhao1998** [comment]
Hello, 感谢你的关注

我在写 model 的时候默认写了 staget = 3，但是在网络结构实例化的时候特别设置了 stage = 1
请参考 https://github.com/caiyuanhao1998/Retinexformer/blob/master/Options/RetinexFormer_LOL_v1.yml#L57C1-L57C11

如果觉得我们的 repo 有用的话，帮忙 fork 支持一下，感谢
