### ISSUE TITLE
test_form_dataset

### ISSUE THREAD

**Issue by Enternal-w** [caiyuanhao1998/Retinexformer#88]
![屏幕截图 2024-06-26 113320](https://github.com/caiyuanhao1998/Retinexformer/assets/63199069/b6ac2f05-d33e-4f2c-96b9-8fe998f1f2ed)
您好，按照主页的路径下载了数据集，还有这样的错误，FileNotFoundError: [Errno 2] No such file or directory: 'Options/RetinexFormer_SDSD_indoor.yml'
我该如何解决

**Comment by caiyuanhao1998** [comment]
你好，感谢关注
使用 windows 系统来跑代码的话容易引起很多 bug，建议是使用 ubuntu 系统，这边这个报错应该是你没有把 basicsr 安装成功。

如果觉得我们的 repo 有用的话，麻烦帮忙点点 star 支持一下，感谢

**Comment by 674123** [comment]
您好，我在运行测试的时候遇见了以下问题，困扰许久，还请解答：
(base) root@autodl-container-8a50119a52-09e6fee2:~/Retinexformer-master# python Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL.pth/net_g_1000.pth --dataset LOL_v1
export CUDA_VISIBLE_DEVICES=0
dataset LOL_v1
Not using Automatic Mixed Precision
===>Testing using weights:  pretrained_weights/LOL.pth/net_g_1000.pth
data/LOLv1/Test/input
data/LOLv1/Test/target
0it [00:00, ?it/s]
/root/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/root/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
PSNR: nan 
SSIM: nan

**Comment by thelin1** [comment]
> 您好，我在运行测试的时候遇见了以下问题，困扰许久，还请解答： (base) root@autodl-container-8a50119a52-09e6fee2:~/Retinexformer-master# python Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL.pth/net_g_1000.pth --dataset LOL_v1 export CUDA_VISIBLE_DEVICES=0 dataset LOL_v1 Not using Automatic Mixed Precision ===>Testing using weights: pretrained_weights/LOL.pth/net_g_1000.pth data/LOLv1/Test/input data/LOLv1/Test/target 0it [00:00, ?it/s] /root/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype, /root/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount) PSNR: nan SSIM: nan

您好，请问这个问题您解决了吗，我在运行测试时遇到了同样的问题，向您请教

**Comment by 674123** [comment]
> > 您好，我在运行测试的时候遇见了以下问题，困扰许久，还请解答： (base) root@autodl-container-8a50119a52-09e6fee2:~/Retinexformer-master# python Enhancement/test_from_dataset.py --opt Options/RetinexFormer_LOL_v1.yml --weights pretrained_weights/LOL.pth/net_g_1000.pth --dataset LOL_v1 export CUDA_VISIBLE_DEVICES=0 dataset LOL_v1 Not using Automatic Mixed Precision ===>Testing using weights: pretrained_weights/LOL.pth/net_g_1000.pth data/LOLv1/Test/input data/LOLv1/Test/target 0it [00:00, ?it/s] /root/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype, /root/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount) PSNR: nan SSIM: nan
> 
> 您好，请问这个问题您解决了吗，我在运行测试时遇到了同样的问题，向您请教
太久没有部署了，我记得我当时是数据集目录不对。
