### ISSUE TITLE
about use 'SMID.pth'

### ISSUE THREAD

**Issue by Mayingj** [caiyuanhao1998/Retinexformer#9]
Thank you very much for your work. I am very interested in it，When I'm trying to use pretrained models about 'SMID.pth',I always can't get the SMID/test_list.txt，How should I get such a file，So I would like to request your help！Thank you！

**Comment by caiyuanhao1998** [comment]
Please download the text_list.txt from [Google Drive](https://drive.google.com/file/d/199qrfizUeZfgq3qVjrM74mZ_nlacgwiP/view?usp=sharing) or [Baidu Disk](https://pan.baidu.com/s/1GQfaQLI6tvB0IrTMPOM_9Q?pwd=ggbh) (code: `ggbh`) and then put it into the folder `data/SMID/SMID_Long_np/`

We also paste it here:

```shell

0013
0009
0020
0007
0010
0012
0154
0036
0037
0039
0047
0048
0049
0050
0051
0052
0065
0066
0075
0076
0078
0088
0092
0099
0091
0103
0104
0105
0106
0107
0151
0145
0147
0139
0129
0083
0153
0157
0180
0175
0181
0196
0170
0166
0172
0177
0167
0169
0191


```
