### ISSUE TITLE
train and test

### ISSUE THREAD

**Issue by Enternal-w** [caiyuanhao1998/Retinexformer#90]
作者您好，非常感谢您的开源成果，遇到一些问题，希望您给到一些建议
在train过程中出现以下错误：
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.80 GiB total capacity; 2.25 GiB already allocated; 11.88 MiB free; 2.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

在test过程中出现以下错误：
Not using Automatic Mixed Precision
2024-07-02 11:47:19,157 INFO: Dataset Dataset_PairedImage - TrainSet is created.
2024-07-02 11:47:19,158 INFO: Number of test images in TrainSet: 485
2024-07-02 11:47:19,158 INFO: Dataset Dataset_PairedImage - ValSet is created.
2024-07-02 11:47:19,158 INFO: Number of test images in ValSet: 15
2024-07-02 11:47:21,803 INFO: Model [ImageCleanModel] is created.
2024-07-02 11:47:21,803 INFO: Testing TrainSet...
Traceback (most recent call last):
  File "/home/jia/Retinexformer/basicsr/test.py", line 62, in <module>
    main()
  File "/home/jia/Retinexformer/basicsr/test.py", line 58, in main
    rgb2bgr=rgb2bgr, use_image=use_image)
  File "/home/jia/Retinexformer/basicsr/models/base_model.py", line 52, in validation
    save_img, rgb2bgr, use_image)
  File "/home/jia/Retinexformer/basicsr/models/image_restoration_model.py", line 314, in nondist_validation
    metric_module, metric_type)(visuals['result'], visuals['gt'], **opt_)
  File "/home/jia/Retinexformer/basicsr/metrics/psnr_ssim.py", line 40, in calculate_psnr
    img1 = img1.detach().cpu().numpy().transpose(1,2,0)
ValueError: axes don't match array

**Comment by caiyuanhao1998** [comment]
你好，请把你执行的详细的 train 和 test 指令以及你是按照哪个环境进行配置的发一下，我可以帮你看看

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下

**Comment by caiyuanhao1998** [comment]
hello, 发一下吗，我可以帮你看看

**Comment by Enternal-w** [comment]
我可能知道是什么问题了，我在ubantu上使用pycharm运行的train&nbsp;test，并没有使用您主页上的指令，我晚点尝试一下


---Original---
From: &quot;Yuanhao ***@***.***&gt;
Date: Tue, Jul 2, 2024 13:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caiyuanhao1998/Retinexformer] train and test (Issue #90)




 
hello, 发一下吗，我可以帮你看看
 
&mdash;

**Comment by Enternal-w** [comment]
非常非常非常感谢您


---Original---
From: &quot;Yuanhao ***@***.***&gt;
Date: Tue, Jul 2, 2024 13:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caiyuanhao1998/Retinexformer] train and test (Issue #90)




 
hello, 发一下吗，我可以帮你看看
 
&mdash;

**Comment by caiyuanhao1998** [comment]
哦哦，好的 :)

**Comment by Enternal-w** [comment]
作者您好，作为一个初学者被一些基础问题所困扰，希望可以得到您启发性的指导。
1.为什么illuminate&nbsp;prior使用的是通道维度dim=1的均值，这样操作是可以简化运算还是
2.可分离卷积5*5的作用就是为了提取特征吗，设计成5*5有什么特殊要求吗
3.light&nbsp;map为什么通过这样三个卷积就得到了，有什么理论性的说法吗


---Original---
From: &quot;Yuanhao ***@***.***&gt;
Date: Tue, Jul 2, 2024 13:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caiyuanhao1998/Retinexformer] train and test (Issue #90)




 
哦哦，好的 :)
 
&mdash;

**Comment by caiyuanhao1998** [comment]
1、illumination prior 是在通道维度上算均值，即 RGB 均值
2、对的，5x5是为了扩大感受野
3、类似于用一个简单的卷积网络直接去学习

**Comment by Enternal-w** [comment]
非常感谢您的回复


---Original---
From: &quot;Yuanhao ***@***.***&gt;
Date: Thu, Jul 11, 2024 09:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caiyuanhao1998/Retinexformer] train and test (Issue #90)




 
1、illumination prior 是在通道维度上算均值，即 RGB 均值
 2、对的，5x5是为了扩大感受野
 3、类似于用一个简单的卷积网络直接去学习
 
&mdash;

**Comment by Enternal-w** [comment]
作者您好，文中L点乘L-等于1是如何约束的，L-就是那个从三个卷积层出来的light&nbsp;map
有什么理论依据吗，还是参考了那些文献


---Original---
From: &quot;Yuanhao ***@***.***&gt;
Date: Thu, Jul 11, 2024 09:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [caiyuanhao1998/Retinexformer] train and test (Issue #90)




 
1、illumination prior 是在通道维度上算均值，即 RGB 均值
 2、对的，5x5是为了扩大感受野
 3、类似于用一个简单的卷积网络直接去学习
 
&mdash;
