### ISSUE TITLE
您好！您方便公布一下对比方法的结果图吗，我想在您的方法上进行改进，并且我想增加多个评价指标，感谢您对底层视觉任务的贡献。

### ISSUE THREAD

**Issue by UPC2024ZQ** [caiyuanhao1998/Retinexformer#91]

**Comment by UPC2024ZQ** [comment]
如果您不方便公布的话，我的邮箱是1795291368@qq.com,您也可以发我邮箱。

**Comment by caiyuanhao1998** [comment]
感谢支持和关注，我已经更新在 readme 里面了 :)

Uformer 也很好改，在 model 文件夹下加入 Uformer 的网络结构文件，然后在 config 里面选中注册的 model 即可
