### ISSUE TITLE
关于深度卷积

### ISSUE THREAD

**Issue by zsn1107** [caiyuanhao1998/Retinexformer#92]
![}LGDZS@{AX`6Z0%VC@TKIU1](https://github.com/caiyuanhao1998/Retinexformer/assets/138637176/5bf1d1c2-a63f-40ab-80db-8859596c8491)
请问这里的深度卷积的groups为何设置为n_fea_in。而不是n_fea_middle呢

**Comment by caiyuanhao1998** [comment]
因为 n_fea_in 相对较大，分层过多会导致训练速度变慢，这种深度分离的操作其实对 GPU 不太友好，虽然显示的 RAM 占用并不多。

如果觉得我们的 repo 有用的话，帮我们点点 star 支持一下
