### ISSUE TITLE
Illumination estimator 如何约束

### ISSUE THREAD

**Issue by ZziTaiLeo** [caiyuanhao1998/Retinexformer#96]
请问第一个estimator是不需要任何约束吗。 如何确保中间产出的feat map和light map 能符合我们的预期。

**Comment by caiyuanhao1998** [comment]
可以理解为整套框架遵循 Retinex 理论，那么第一阶段的 light map 可在后续的 enhanced image 中得到监督。直接给 light map施加监督是难以实现的，因为没有这方面的 GT，所以采取这种间接方式进行监督
