### ISSUE TITLE
结果不一致

### ISSUE THREAD

**Issue by A1leilei** [caiyuanhao1998/Retinexformer#97]
为啥在rtx4070上跑出的结果不是25，而是23.01左右。这个对电脑性能有要求吗？

**Comment by caiyuanhao1998** [comment]
你好，感谢关注，我们在 LOL-v2-real 以及 FiveK 数据集上的结果是在 3090 上训练的，其余模型是在 RTX 8000 上边训练的。请按照我们的 readme 里面的步骤配置环境并执行环境。

如果觉得我们的 repo 有用的话，帮忙点点 star 支持一下

**Comment by JJCcxk** [comment]
> 为啥在rtx4070上跑出的结果不是25，而是23.01左右。这个对电脑性能有要求吗？

你的4070跑是用的什么参数，我也是用的4070但是GPU利用呼高呼低0-99之间
