### ISSUE TITLE
ExDark数据集的训练细节

### ISSUE THREAD

**Issue by Rutile810** [caiyuanhao1998/Retinexformer#99]
你好，我想请教一下，您使用哪个数据集训练RetinexFormer以增强ExDark数据集？是LOLv1吗？此外，我注意到您在论文中提到，经过增强后的ExDark训练检测性能达到了66.1%。请问这是在没有加载YOLOv3预训练权重的情况下获得的吗？另外，您能否告知YOLOv3的训练epochs数量，是默认的25吗？

**Comment by caiyuanhao1998** [comment]
你好，感谢关注。可以用 LOLv1，推荐用 LOL-v2-synthetic。对的，不使用预训练模型，因为使用了该模型就无法确定是 enhancer 的影响了。epoch 可以用默认的 25。

**Comment by Rutile810** [comment]
感谢
